//! Vanilla 1.12 `FactionTemplate.dbc` id (`UNIT_FIELD_FACTIONTEMPLATE`).
//!
//! Creature templates and player units use this id on the wire, not `Faction.dbc`.
use serde::{Deserialize, Serialize};

use super::DbEnum;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CreatureFaction {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "PLAYER_HUMAN")]
    PlayerHuman,
    #[serde(rename = "PLAYER_ORC")]
    PlayerOrc,
    #[serde(rename = "PLAYER_DWARF")]
    PlayerDwarf,
    #[serde(rename = "PLAYER_NIGHT_ELF")]
    PlayerNightElf,
    #[serde(rename = "PLAYER_UNDEAD")]
    PlayerUndead,
    #[serde(rename = "PLAYER_TAUREN")]
    PlayerTauren,
    #[serde(rename = "CREATURE")]
    Creature,
    #[serde(rename = "ESCORTEE")]
    Escortee,
    #[serde(rename = "STORMWIND")]
    Stormwind,
    #[serde(rename = "STORMWIND_12")]
    Stormwind12,
    #[serde(rename = "MONSTER")]
    Monster,
    #[serde(rename = "CREATURE_15")]
    Creature15,
    #[serde(rename = "MONSTER_16")]
    Monster16,
    #[serde(rename = "DEFIAS_BROTHERHOOD")]
    DefiasBrotherhood,
    #[serde(rename = "MURLOC")]
    Murloc,
    #[serde(rename = "GNOLL_REDRIDGE")]
    GnollRedridge,
    #[serde(rename = "GNOLL_RIVERPAW")]
    GnollRiverpaw,
    #[serde(rename = "UNDEAD_SCOURGE")]
    UndeadScourge,
    #[serde(rename = "BEAST_SPIDER")]
    BeastSpider,
    #[serde(rename = "GNOMEREGAN_EXILES")]
    GnomereganExiles,
    #[serde(rename = "WORGEN")]
    Worgen,
    #[serde(rename = "KOBOLD")]
    Kobold,
    #[serde(rename = "KOBOLD_26")]
    Kobold26,
    #[serde(rename = "DEFIAS_BROTHERHOOD_27")]
    DefiasBrotherhood27,
    #[serde(rename = "TROLL_BLOODSCALP")]
    TrollBloodscalp,
    #[serde(rename = "ORGRIMMAR")]
    Orgrimmar,
    #[serde(rename = "TROLL_SKULLSPLITTER")]
    TrollSkullsplitter,
    #[serde(rename = "PREY")]
    Prey,
    #[serde(rename = "BEAST_WOLF")]
    BeastWolf,
    #[serde(rename = "ESCORTEE_33")]
    Escortee33,
    #[serde(rename = "DEFIAS_BROTHERHOOD_34")]
    DefiasBrotherhood34,
    #[serde(rename = "FRIENDLY")]
    Friendly,
    #[serde(rename = "TROGG")]
    Trogg,
    #[serde(rename = "TROLL_FROSTMANE")]
    TrollFrostmane,
    #[serde(rename = "BEAST_WOLF_38")]
    BeastWolf38,
    #[serde(rename = "GNOLL_SHADOWHIDE")]
    GnollShadowhide,
    #[serde(rename = "ORC_BLACKROCK")]
    OrcBlackrock,
    #[serde(rename = "VILLIAN")]
    Villian,
    #[serde(rename = "VICTIM")]
    Victim,
    #[serde(rename = "VILLIAN_43")]
    Villian43,
    #[serde(rename = "BEAST_BEAR")]
    BeastBear,
    #[serde(rename = "OGRE")]
    Ogre,
    #[serde(rename = "KURZENS_MERCENARIES")]
    KurzensMercenaries,
    #[serde(rename = "VENTURE_COMPANY")]
    VentureCompany,
    #[serde(rename = "BEAST_RAPTOR")]
    BeastRaptor,
    #[serde(rename = "BASILISK")]
    Basilisk,
    #[serde(rename = "DRAGONFLIGHT_GREEN")]
    DragonflightGreen,
    #[serde(rename = "LOST_ONES")]
    LostOnes,
    #[serde(rename = "GIZLOCKS_DUMMY")]
    GizlocksDummy,
    #[serde(rename = "HUMAN_NIGHT_WATCH")]
    HumanNightWatch,
    #[serde(rename = "DARK_IRON_DWARVES")]
    DarkIronDwarves,
    #[serde(rename = "IRONFORGE")]
    Ironforge,
    #[serde(rename = "HUMAN_NIGHT_WATCH_56")]
    HumanNightWatch56,
    #[serde(rename = "IRONFORGE_57")]
    Ironforge57,
    #[serde(rename = "CREATURE_58")]
    Creature58,
    #[serde(rename = "TROGG_59")]
    Trogg59,
    #[serde(rename = "DRAGONFLIGHT_RED")]
    DragonflightRed,
    #[serde(rename = "GNOLL_MOSSHIDE")]
    GnollMosshide,
    #[serde(rename = "ORC_DRAGONMAW")]
    OrcDragonmaw,
    #[serde(rename = "GNOME_LEPER")]
    GnomeLeper,
    #[serde(rename = "GNOMEREGAN_EXILES_64")]
    GnomereganExiles64,
    #[serde(rename = "ORGRIMMAR_65")]
    Orgrimmar65,
    #[serde(rename = "LEOPARD")]
    Leopard,
    #[serde(rename = "SCARLET_CRUSADE")]
    ScarletCrusade,
    #[serde(rename = "UNDERCITY")]
    Undercity,
    #[serde(rename = "RATCHET")]
    Ratchet,
    #[serde(rename = "GNOLL_ROTHIDE")]
    GnollRothide,
    #[serde(rename = "UNDERCITY_71")]
    Undercity71,
    #[serde(rename = "BEAST_GORILLA")]
    BeastGorilla,
    #[serde(rename = "BEAST_CARRION_BIRD")]
    BeastCarrionBird,
    #[serde(rename = "NAGA")]
    Naga,
    #[serde(rename = "DALARAN")]
    Dalaran,
    #[serde(rename = "FORLORN_SPIRIT")]
    ForlornSpirit,
    #[serde(rename = "DARKHOWL")]
    Darkhowl,
    #[serde(rename = "DARNASSUS")]
    Darnassus,
    #[serde(rename = "DARNASSUS_80")]
    Darnassus80,
    #[serde(rename = "GRELL")]
    Grell,
    #[serde(rename = "FURBOLG")]
    Furbolg,
    #[serde(rename = "HORDE_GENERIC")]
    HordeGeneric,
    #[serde(rename = "ALLIANCE_GENERIC")]
    AllianceGeneric,
    #[serde(rename = "ORGRIMMAR_85")]
    Orgrimmar85,
    #[serde(rename = "GIZLOCKS_CHARM")]
    GizlocksCharm,
    #[serde(rename = "SYNDICATE")]
    Syndicate,
    #[serde(rename = "HILLSBRAD_MILITIA")]
    HillsbradMilitia,
    #[serde(rename = "SCARLET_CRUSADE_89")]
    ScarletCrusade89,
    #[serde(rename = "DEMON")]
    Demon,
    #[serde(rename = "ELEMENTAL")]
    Elemental,
    #[serde(rename = "SPIRIT")]
    Spirit,
    #[serde(rename = "MONSTER_93")]
    Monster93,
    #[serde(rename = "TREASURE")]
    Treasure,
    #[serde(rename = "GNOLL_MUDSNOUT")]
    GnollMudsnout,
    #[serde(rename = "HILLSBRAD_SOUTHSHORE_MAYOR")]
    HillsbradSouthshoreMayor,
    #[serde(rename = "SYNDICATE_97")]
    Syndicate97,
    #[serde(rename = "UNDERCITY_98")]
    Undercity98,
    #[serde(rename = "VICTIM_99")]
    Victim99,
    #[serde(rename = "TREASURE_100")]
    Treasure100,
    #[serde(rename = "TREASURE_101")]
    Treasure101,
    #[serde(rename = "TREASURE_102")]
    Treasure102,
    #[serde(rename = "DRAGONFLIGHT_BLACK")]
    DragonflightBlack,
    #[serde(rename = "THUNDER_BLUFF")]
    ThunderBluff,
    #[serde(rename = "THUNDER_BLUFF_105")]
    ThunderBluff105,
    #[serde(rename = "HORDE_GENERIC_106")]
    HordeGeneric106,
    #[serde(rename = "TROLL_FROSTMANE_107")]
    TrollFrostmane107,
    #[serde(rename = "SYNDICATE_108")]
    Syndicate108,
    #[serde(rename = "QUILBOAR_RAZORMANE_2")]
    QuilboarRazormane2,
    #[serde(rename = "QUILBOAR_RAZORMANE_2_110")]
    QuilboarRazormane2110,
    #[serde(rename = "QUILBOAR_BRISTLEBACK")]
    QuilboarBristleback,
    #[serde(rename = "QUILBOAR_BRISTLEBACK_112")]
    QuilboarBristleback112,
    #[serde(rename = "ESCORTEE_113")]
    Escortee113,
    #[serde(rename = "TREASURE_114")]
    Treasure114,
    #[serde(rename = "PLAYER_GNOME")]
    PlayerGnome,
    #[serde(rename = "PLAYER_TROLL")]
    PlayerTroll,
    #[serde(rename = "UNDERCITY_118")]
    Undercity118,
    #[serde(rename = "BLOODSAIL_BUCCANEERS")]
    BloodsailBuccaneers,
    #[serde(rename = "BOOTY_BAY")]
    BootyBay,
    #[serde(rename = "BOOTY_BAY_121")]
    BootyBay121,
    #[serde(rename = "IRONFORGE_122")]
    Ironforge122,
    #[serde(rename = "STORMWIND_123")]
    Stormwind123,
    #[serde(rename = "DARNASSUS_124")]
    Darnassus124,
    #[serde(rename = "ORGRIMMAR_125")]
    Orgrimmar125,
    #[serde(rename = "DARKSPEAR_TROLLS")]
    DarkspearTrolls,
    #[serde(rename = "VILLIAN_127")]
    Villian127,
    #[serde(rename = "BLACKFATHOM")]
    Blackfathom,
    #[serde(rename = "MAKRURA")]
    Makrura,
    #[serde(rename = "CENTAUR_KOLKAR")]
    CentaurKolkar,
    #[serde(rename = "CENTAUR_GALAK")]
    CentaurGalak,
    #[serde(rename = "GELKIS_CLAN_CENTAUR")]
    GelkisClanCentaur,
    #[serde(rename = "MAGRAM_CLAN_CENTAUR")]
    MagramClanCentaur,
    #[serde(rename = "MARAUDINE")]
    Maraudine,
    #[serde(rename = "MONSTER_148")]
    Monster148,
    #[serde(rename = "THERAMORE")]
    Theramore,
    #[serde(rename = "THERAMORE_150")]
    Theramore150,
    #[serde(rename = "THERAMORE_151")]
    Theramore151,
    #[serde(rename = "QUILBOAR_RAZORFEN")]
    QuilboarRazorfen,
    #[serde(rename = "QUILBOAR_RAZORFEN_153")]
    QuilboarRazorfen153,
    #[serde(rename = "QUILBOAR_DEATHSHEAD")]
    QuilboarDeathshead,
    #[serde(rename = "ENEMY")]
    Enemy,
    #[serde(rename = "AMBIENT")]
    Ambient,
    #[serde(rename = "CREATURE_189")]
    Creature189,
    #[serde(rename = "AMBIENT_190")]
    Ambient190,
    #[serde(rename = "NETHERGARDE_CARAVAN")]
    NethergardeCaravan,
    #[serde(rename = "NETHERGARDE_CARAVAN_209")]
    NethergardeCaravan209,
    #[serde(rename = "ALLIANCE_GENERIC_210")]
    AllianceGeneric210,
    #[serde(rename = "SOUTHSEA_FREEBOOTERS")]
    SouthseaFreebooters,
    #[serde(rename = "ESCORTEE_231")]
    Escortee231,
    #[serde(rename = "ESCORTEE_232")]
    Escortee232,
    #[serde(rename = "UNDEAD_SCOURGE_233")]
    UndeadScourge233,
    #[serde(rename = "ESCORTEE_250")]
    Escortee250,
    #[serde(rename = "WAILING_CAVERNS")]
    WailingCaverns,
    #[serde(rename = "ESCORTEE_290")]
    Escortee290,
    #[serde(rename = "SILITHID")]
    Silithid,
    #[serde(rename = "SILITHID_311")]
    Silithid311,
    #[serde(rename = "BEAST_SPIDER_312")]
    BeastSpider312,
    #[serde(rename = "WAILING_CAVERNS_330")]
    WailingCaverns330,
    #[serde(rename = "BLACKFATHOM_350")]
    Blackfathom350,
    #[serde(rename = "ARMIES_OF_CTHUN")]
    ArmiesOfCthun,
    #[serde(rename = "SILVERMOON_REMNANT")]
    SilvermoonRemnant,
    #[serde(rename = "BOOTY_BAY_390")]
    BootyBay390,
    #[serde(rename = "BASILISK_410")]
    Basilisk410,
    #[serde(rename = "BEAST_BAT")]
    BeastBat,
    #[serde(rename = "THE_DEFILERS")]
    TheDefilers,
    #[serde(rename = "SCORPID")]
    Scorpid,
    #[serde(rename = "TIMBERMAW_HOLD")]
    TimbermawHold,
    #[serde(rename = "TITAN")]
    Titan,
    #[serde(rename = "TITAN_416")]
    Titan416,
    #[serde(rename = "TASKMASTER_FIZZULE")]
    TaskmasterFizzule,
    #[serde(rename = "WAILING_CAVERNS_450")]
    WailingCaverns450,
    #[serde(rename = "TITAN_470")]
    Titan470,
    #[serde(rename = "RAVENHOLDT")]
    Ravenholdt,
    #[serde(rename = "SYNDICATE_472")]
    Syndicate472,
    #[serde(rename = "RAVENHOLDT_473")]
    Ravenholdt473,
    #[serde(rename = "GADGETZAN")]
    Gadgetzan,
    #[serde(rename = "GADGETZAN_475")]
    Gadgetzan475,
    #[serde(rename = "GNOMEREGAN_BUG")]
    GnomereganBug,
    #[serde(rename = "ESCORTEE_495")]
    Escortee495,
    #[serde(rename = "HARPY")]
    Harpy,
    #[serde(rename = "ALLIANCE_GENERIC_534")]
    AllianceGeneric534,
    #[serde(rename = "BURNING_BLADE")]
    BurningBlade,
    #[serde(rename = "SHADOWSILK_POACHER")]
    ShadowsilkPoacher,
    #[serde(rename = "SEARING_SPIDER")]
    SearingSpider,
    #[serde(rename = "TROGG_594")]
    Trogg594,
    #[serde(rename = "VICTIM_614")]
    Victim614,
    #[serde(rename = "MONSTER_634")]
    Monster634,
    #[serde(rename = "CENARION_CIRCLE")]
    CenarionCircle,
    #[serde(rename = "TIMBERMAW_HOLD_636")]
    TimbermawHold636,
    #[serde(rename = "RATCHET_637")]
    Ratchet637,
    #[serde(rename = "TROLL_WITHERBARK")]
    TrollWitherbark,
    #[serde(rename = "CENTAUR_KOLKAR_655")]
    CentaurKolkar655,
    #[serde(rename = "DARK_IRON_DWARVES_674")]
    DarkIronDwarves674,
    #[serde(rename = "ALLIANCE_GENERIC_694")]
    AllianceGeneric694,
    #[serde(rename = "HYDRAXIAN_WATERLORDS")]
    HydraxianWaterlords,
    #[serde(rename = "HORDE_GENERIC_714")]
    HordeGeneric714,
    #[serde(rename = "DARK_IRON_DWARVES_734")]
    DarkIronDwarves734,
    #[serde(rename = "GOBLIN_DARK_IRON_BAR_PATRON")]
    GoblinDarkIronBarPatron,
    #[serde(rename = "GOBLIN_DARK_IRON_BAR_PATRON_736")]
    GoblinDarkIronBarPatron736,
    #[serde(rename = "DARK_IRON_DWARVES_754")]
    DarkIronDwarves754,
    #[serde(rename = "ESCORTEE_774")]
    Escortee774,
    #[serde(rename = "ESCORTEE_775")]
    Escortee775,
    #[serde(rename = "BROOD_OF_NOZDORMU")]
    BroodOfNozdormu,
    #[serde(rename = "MIGHT_OF_KALIMDOR")]
    MightOfKalimdor,
    #[serde(rename = "GIANT")]
    Giant,
    #[serde(rename = "ARGENT_DAWN")]
    ArgentDawn,
    #[serde(rename = "TROLL_VILEBRANCH")]
    TrollVilebranch,
    #[serde(rename = "ARGENT_DAWN_814")]
    ArgentDawn814,
    #[serde(rename = "ELEMENTAL_834")]
    Elemental834,
    #[serde(rename = "EVERLOOK")]
    Everlook,
    #[serde(rename = "EVERLOOK_855")]
    Everlook855,
    #[serde(rename = "WINTERSABER_TRAINERS")]
    WintersaberTrainers,
    #[serde(rename = "GNOMEREGAN_EXILES_875")]
    GnomereganExiles875,
    #[serde(rename = "DARKSPEAR_TROLLS_876")]
    DarkspearTrolls876,
    #[serde(rename = "DARKSPEAR_TROLLS_877")]
    DarkspearTrolls877,
    #[serde(rename = "THERAMORE_894")]
    Theramore894,
    #[serde(rename = "TRAINING_DUMMY")]
    TrainingDummy,
    #[serde(rename = "FURBOLG_UNCORRUPTED")]
    FurbolgUncorrupted,
    #[serde(rename = "DEMON_954")]
    Demon954,
    #[serde(rename = "UNDEAD_SCOURGE_974")]
    UndeadScourge974,
    #[serde(rename = "CENARION_CIRCLE_994")]
    CenarionCircle994,
    #[serde(rename = "THUNDER_BLUFF_995")]
    ThunderBluff995,
    #[serde(rename = "CENARION_CIRCLE_996")]
    CenarionCircle996,
    #[serde(rename = "SHATTERSPEAR_TROLLS")]
    ShatterspearTrolls,
    #[serde(rename = "SHATTERSPEAR_TROLLS_1015")]
    ShatterspearTrolls1015,
    #[serde(rename = "HORDE_GENERIC_1034")]
    HordeGeneric1034,
    #[serde(rename = "ALLIANCE_GENERIC_1054")]
    AllianceGeneric1054,
    #[serde(rename = "ALLIANCE_GENERIC_1055")]
    AllianceGeneric1055,
    #[serde(rename = "ORGRIMMAR_1074")]
    Orgrimmar1074,
    #[serde(rename = "THERAMORE_1075")]
    Theramore1075,
    #[serde(rename = "DARNASSUS_1076")]
    Darnassus1076,
    #[serde(rename = "THERAMORE_1077")]
    Theramore1077,
    #[serde(rename = "STORMWIND_1078")]
    Stormwind1078,
    #[serde(rename = "FRIENDLY_1080")]
    Friendly1080,
    #[serde(rename = "ELEMENTAL_1081")]
    Elemental1081,
    #[serde(rename = "BEAST_BOAR")]
    BeastBoar,
    #[serde(rename = "TRAINING_DUMMY_1095")]
    TrainingDummy1095,
    #[serde(rename = "THERAMORE_1096")]
    Theramore1096,
    #[serde(rename = "DARNASSUS_1097")]
    Darnassus1097,
    #[serde(rename = "DRAGONFLIGHT_BLACK_BAIT")]
    DragonflightBlackBait,
    #[serde(rename = "UNDERCITY_1134")]
    Undercity1134,
    #[serde(rename = "UNDERCITY_1154")]
    Undercity1154,
    #[serde(rename = "ORGRIMMAR_1174")]
    Orgrimmar1174,
    #[serde(rename = "BATTLEGROUND_NEUTRAL")]
    BattlegroundNeutral,
    #[serde(rename = "FROSTWOLF_CLAN")]
    FrostwolfClan,
    #[serde(rename = "FROSTWOLF_CLAN_1215")]
    FrostwolfClan1215,
    #[serde(rename = "STORMPIKE_GUARD")]
    StormpikeGuard,
    #[serde(rename = "STORMPIKE_GUARD_1217")]
    StormpikeGuard1217,
    #[serde(rename = "SULFURON_FIRELORDS")]
    SulfuronFirelords,
    #[serde(rename = "SULFURON_FIRELORDS_1235")]
    SulfuronFirelords1235,
    #[serde(rename = "SULFURON_FIRELORDS_1236")]
    SulfuronFirelords1236,
    #[serde(rename = "CENARION_CIRCLE_1254")]
    CenarionCircle1254,
    #[serde(rename = "CREATURE_1274")]
    Creature1274,
    #[serde(rename = "CREATURE_1275")]
    Creature1275,
    #[serde(rename = "GIZLOCK")]
    Gizlock,
    #[serde(rename = "HORDE_GENERIC_1314")]
    HordeGeneric1314,
    #[serde(rename = "ALLIANCE_GENERIC_1315")]
    AllianceGeneric1315,
    #[serde(rename = "STORMPIKE_GUARD_1334")]
    StormpikeGuard1334,
    #[serde(rename = "FROSTWOLF_CLAN_1335")]
    FrostwolfClan1335,
    #[serde(rename = "SHENDRALAR")]
    Shendralar,
    #[serde(rename = "SHENDRALAR_1355")]
    Shendralar1355,
    #[serde(rename = "OGRE_CAPTAIN_KROMCRUSH")]
    OgreCaptainKromcrush,
    #[serde(rename = "TREASURE_1375")]
    Treasure1375,
    #[serde(rename = "DRAGONFLIGHT_BLACK_1394")]
    DragonflightBlack1394,
    #[serde(rename = "SILITHID_ATTACKERS")]
    SilithidAttackers,
    #[serde(rename = "SPIRIT_GUIDE_ALLIANCE")]
    SpiritGuideAlliance,
    #[serde(rename = "SPIRIT_GUIDE_HORDE")]
    SpiritGuideHorde,
    #[serde(rename = "JAEDENAR")]
    Jaedenar,
    #[serde(rename = "VICTIM_1454")]
    Victim1454,
    #[serde(rename = "THORIUM_BROTHERHOOD")]
    ThoriumBrotherhood,
    #[serde(rename = "THORIUM_BROTHERHOOD_1475")]
    ThoriumBrotherhood1475,
    #[serde(rename = "HORDE_GENERIC_1494")]
    HordeGeneric1494,
    #[serde(rename = "HORDE_GENERIC_1495")]
    HordeGeneric1495,
    #[serde(rename = "HORDE_GENERIC_1496")]
    HordeGeneric1496,
    #[serde(rename = "SILVERWING_SENTINELS")]
    SilverwingSentinels,
    #[serde(rename = "WARSONG_OUTRIDERS")]
    WarsongOutriders,
    #[serde(rename = "STORMPIKE_GUARD_1534")]
    StormpikeGuard1534,
    #[serde(rename = "FROSTWOLF_CLAN_1554")]
    FrostwolfClan1554,
    #[serde(rename = "DARKMOON_FAIRE")]
    DarkmoonFaire,
    #[serde(rename = "ZANDALAR_TRIBE")]
    ZandalarTribe,
    #[serde(rename = "STORMWIND_1575")]
    Stormwind1575,
    #[serde(rename = "SILVERMOON_REMNANT_1576")]
    SilvermoonRemnant1576,
    #[serde(rename = "THE_LEAGUE_OF_ARATHOR")]
    TheLeagueOfArathor,
    #[serde(rename = "DARNASSUS_1594")]
    Darnassus1594,
    #[serde(rename = "ORGRIMMAR_1595")]
    Orgrimmar1595,
    #[serde(rename = "STORMPIKE_GUARD_1596")]
    StormpikeGuard1596,
    #[serde(rename = "FROSTWOLF_CLAN_1597")]
    FrostwolfClan1597,
    #[serde(rename = "THE_DEFILERS_1598")]
    TheDefilers1598,
    #[serde(rename = "THE_LEAGUE_OF_ARATHOR_1599")]
    TheLeagueOfArathor1599,
    #[serde(rename = "DARNASSUS_1600")]
    Darnassus1600,
    #[serde(rename = "BROOD_OF_NOZDORMU_1601")]
    BroodOfNozdormu1601,
    #[serde(rename = "SILVERMOON_CITY")]
    SilvermoonCity,
    #[serde(rename = "SILVERMOON_CITY_1603")]
    SilvermoonCity1603,
    #[serde(rename = "SILVERMOON_CITY_1604")]
    SilvermoonCity1604,
    #[serde(rename = "DRAGONFLIGHT_BRONZE")]
    DragonflightBronze,
    #[serde(rename = "CREATURE_1606")]
    Creature1606,
    #[serde(rename = "CREATURE_1607")]
    Creature1607,
    #[serde(rename = "CENARION_CIRCLE_1608")]
    CenarionCircle1608,
    #[serde(rename = "PLAYER_BLOOD_ELF")]
    PlayerBloodElf,
    #[serde(rename = "IRONFORGE_1611")]
    Ironforge1611,
    #[serde(rename = "ORGRIMMAR_1612")]
    Orgrimmar1612,
    #[serde(rename = "MIGHT_OF_KALIMDOR_1613")]
    MightOfKalimdor1613,
    #[serde(rename = "MONSTER_1614")]
    Monster1614,
    #[serde(rename = "STEAMWHEEDLE_CARTEL")]
    SteamwheedleCartel,
    #[serde(rename = "RC_OBJECTS")]
    RcObjects,
    #[serde(rename = "RC_ENEMIES")]
    RcEnemies,
    #[serde(rename = "IRONFORGE_1618")]
    Ironforge1618,
    #[serde(rename = "ORGRIMMAR_1619")]
    Orgrimmar1619,
    #[serde(rename = "ENEMY_1620")]
    Enemy1620,
    #[serde(rename = "BLUE")]
    Blue,
    #[serde(rename = "RED")]
    Red,
    #[serde(rename = "TRANQUILLIEN")]
    Tranquillien,
    #[serde(rename = "ARGENT_DAWN_1624")]
    ArgentDawn1624,
    #[serde(rename = "ARGENT_DAWN_1625")]
    ArgentDawn1625,
    #[serde(rename = "UNDEAD_SCOURGE_1626")]
    UndeadScourge1626,
    #[serde(rename = "FARSTRIDERS")]
    Farstriders,
    #[serde(rename = "TRANQUILLIEN_1628")]
    Tranquillien1628,
    #[serde(rename = "PLAYER_DRAENEI")]
    PlayerDraenei,
    #[serde(rename = "SCOURGE_INVADERS")]
    ScourgeInvaders,
    #[serde(rename = "SCOURGE_INVADERS_1634")]
    ScourgeInvaders1634,
    #[serde(rename = "STEAMWHEEDLE_CARTEL_1635")]
    SteamwheedleCartel1635,
    #[serde(rename = "FARSTRIDERS_1636")]
    Farstriders1636,
    #[serde(rename = "FARSTRIDERS_1637")]
    Farstriders1637,
    #[serde(rename = "EXODAR")]
    Exodar,
    #[serde(rename = "EXODAR_1639")]
    Exodar1639,
    #[serde(rename = "EXODAR_1640")]
    Exodar1640,
    #[serde(rename = "WARSONG_OUTRIDERS_1641")]
    WarsongOutriders1641,
    #[serde(rename = "SILVERWING_SENTINELS_1642")]
    SilverwingSentinels1642,
}

impl CreatureFaction {
    pub const fn as_protocol(self) -> u32 {
        match self {
            Self::None => 0,
            Self::PlayerHuman => 1,
            Self::PlayerOrc => 2,
            Self::PlayerDwarf => 3,
            Self::PlayerNightElf => 4,
            Self::PlayerUndead => 5,
            Self::PlayerTauren => 6,
            Self::Creature => 7,
            Self::Escortee => 10,
            Self::Stormwind => 11,
            Self::Stormwind12 => 12,
            Self::Monster => 14,
            Self::Creature15 => 15,
            Self::Monster16 => 16,
            Self::DefiasBrotherhood => 17,
            Self::Murloc => 18,
            Self::GnollRedridge => 19,
            Self::GnollRiverpaw => 20,
            Self::UndeadScourge => 21,
            Self::BeastSpider => 22,
            Self::GnomereganExiles => 23,
            Self::Worgen => 24,
            Self::Kobold => 25,
            Self::Kobold26 => 26,
            Self::DefiasBrotherhood27 => 27,
            Self::TrollBloodscalp => 28,
            Self::Orgrimmar => 29,
            Self::TrollSkullsplitter => 30,
            Self::Prey => 31,
            Self::BeastWolf => 32,
            Self::Escortee33 => 33,
            Self::DefiasBrotherhood34 => 34,
            Self::Friendly => 35,
            Self::Trogg => 36,
            Self::TrollFrostmane => 37,
            Self::BeastWolf38 => 38,
            Self::GnollShadowhide => 39,
            Self::OrcBlackrock => 40,
            Self::Villian => 41,
            Self::Victim => 42,
            Self::Villian43 => 43,
            Self::BeastBear => 44,
            Self::Ogre => 45,
            Self::KurzensMercenaries => 46,
            Self::VentureCompany => 47,
            Self::BeastRaptor => 48,
            Self::Basilisk => 49,
            Self::DragonflightGreen => 50,
            Self::LostOnes => 51,
            Self::GizlocksDummy => 52,
            Self::HumanNightWatch => 53,
            Self::DarkIronDwarves => 54,
            Self::Ironforge => 55,
            Self::HumanNightWatch56 => 56,
            Self::Ironforge57 => 57,
            Self::Creature58 => 58,
            Self::Trogg59 => 59,
            Self::DragonflightRed => 60,
            Self::GnollMosshide => 61,
            Self::OrcDragonmaw => 62,
            Self::GnomeLeper => 63,
            Self::GnomereganExiles64 => 64,
            Self::Orgrimmar65 => 65,
            Self::Leopard => 66,
            Self::ScarletCrusade => 67,
            Self::Undercity => 68,
            Self::Ratchet => 69,
            Self::GnollRothide => 70,
            Self::Undercity71 => 71,
            Self::BeastGorilla => 72,
            Self::BeastCarrionBird => 73,
            Self::Naga => 74,
            Self::Dalaran => 76,
            Self::ForlornSpirit => 77,
            Self::Darkhowl => 78,
            Self::Darnassus => 79,
            Self::Darnassus80 => 80,
            Self::Grell => 81,
            Self::Furbolg => 82,
            Self::HordeGeneric => 83,
            Self::AllianceGeneric => 84,
            Self::Orgrimmar85 => 85,
            Self::GizlocksCharm => 86,
            Self::Syndicate => 87,
            Self::HillsbradMilitia => 88,
            Self::ScarletCrusade89 => 89,
            Self::Demon => 90,
            Self::Elemental => 91,
            Self::Spirit => 92,
            Self::Monster93 => 93,
            Self::Treasure => 94,
            Self::GnollMudsnout => 95,
            Self::HillsbradSouthshoreMayor => 96,
            Self::Syndicate97 => 97,
            Self::Undercity98 => 98,
            Self::Victim99 => 99,
            Self::Treasure100 => 100,
            Self::Treasure101 => 101,
            Self::Treasure102 => 102,
            Self::DragonflightBlack => 103,
            Self::ThunderBluff => 104,
            Self::ThunderBluff105 => 105,
            Self::HordeGeneric106 => 106,
            Self::TrollFrostmane107 => 107,
            Self::Syndicate108 => 108,
            Self::QuilboarRazormane2 => 109,
            Self::QuilboarRazormane2110 => 110,
            Self::QuilboarBristleback => 111,
            Self::QuilboarBristleback112 => 112,
            Self::Escortee113 => 113,
            Self::Treasure114 => 114,
            Self::PlayerGnome => 115,
            Self::PlayerTroll => 116,
            Self::Undercity118 => 118,
            Self::BloodsailBuccaneers => 119,
            Self::BootyBay => 120,
            Self::BootyBay121 => 121,
            Self::Ironforge122 => 122,
            Self::Stormwind123 => 123,
            Self::Darnassus124 => 124,
            Self::Orgrimmar125 => 125,
            Self::DarkspearTrolls => 126,
            Self::Villian127 => 127,
            Self::Blackfathom => 128,
            Self::Makrura => 129,
            Self::CentaurKolkar => 130,
            Self::CentaurGalak => 131,
            Self::GelkisClanCentaur => 132,
            Self::MagramClanCentaur => 133,
            Self::Maraudine => 134,
            Self::Monster148 => 148,
            Self::Theramore => 149,
            Self::Theramore150 => 150,
            Self::Theramore151 => 151,
            Self::QuilboarRazorfen => 152,
            Self::QuilboarRazorfen153 => 153,
            Self::QuilboarDeathshead => 154,
            Self::Enemy => 168,
            Self::Ambient => 188,
            Self::Creature189 => 189,
            Self::Ambient190 => 190,
            Self::NethergardeCaravan => 208,
            Self::NethergardeCaravan209 => 209,
            Self::AllianceGeneric210 => 210,
            Self::SouthseaFreebooters => 230,
            Self::Escortee231 => 231,
            Self::Escortee232 => 232,
            Self::UndeadScourge233 => 233,
            Self::Escortee250 => 250,
            Self::WailingCaverns => 270,
            Self::Escortee290 => 290,
            Self::Silithid => 310,
            Self::Silithid311 => 311,
            Self::BeastSpider312 => 312,
            Self::WailingCaverns330 => 330,
            Self::Blackfathom350 => 350,
            Self::ArmiesOfCthun => 370,
            Self::SilvermoonRemnant => 371,
            Self::BootyBay390 => 390,
            Self::Basilisk410 => 410,
            Self::BeastBat => 411,
            Self::TheDefilers => 412,
            Self::Scorpid => 413,
            Self::TimbermawHold => 414,
            Self::Titan => 415,
            Self::Titan416 => 416,
            Self::TaskmasterFizzule => 430,
            Self::WailingCaverns450 => 450,
            Self::Titan470 => 470,
            Self::Ravenholdt => 471,
            Self::Syndicate472 => 472,
            Self::Ravenholdt473 => 473,
            Self::Gadgetzan => 474,
            Self::Gadgetzan475 => 475,
            Self::GnomereganBug => 494,
            Self::Escortee495 => 495,
            Self::Harpy => 514,
            Self::AllianceGeneric534 => 534,
            Self::BurningBlade => 554,
            Self::ShadowsilkPoacher => 574,
            Self::SearingSpider => 575,
            Self::Trogg594 => 594,
            Self::Victim614 => 614,
            Self::Monster634 => 634,
            Self::CenarionCircle => 635,
            Self::TimbermawHold636 => 636,
            Self::Ratchet637 => 637,
            Self::TrollWitherbark => 654,
            Self::CentaurKolkar655 => 655,
            Self::DarkIronDwarves674 => 674,
            Self::AllianceGeneric694 => 694,
            Self::HydraxianWaterlords => 695,
            Self::HordeGeneric714 => 714,
            Self::DarkIronDwarves734 => 734,
            Self::GoblinDarkIronBarPatron => 735,
            Self::GoblinDarkIronBarPatron736 => 736,
            Self::DarkIronDwarves754 => 754,
            Self::Escortee774 => 774,
            Self::Escortee775 => 775,
            Self::BroodOfNozdormu => 776,
            Self::MightOfKalimdor => 777,
            Self::Giant => 778,
            Self::ArgentDawn => 794,
            Self::TrollVilebranch => 795,
            Self::ArgentDawn814 => 814,
            Self::Elemental834 => 834,
            Self::Everlook => 854,
            Self::Everlook855 => 855,
            Self::WintersaberTrainers => 874,
            Self::GnomereganExiles875 => 875,
            Self::DarkspearTrolls876 => 876,
            Self::DarkspearTrolls877 => 877,
            Self::Theramore894 => 894,
            Self::TrainingDummy => 914,
            Self::FurbolgUncorrupted => 934,
            Self::Demon954 => 954,
            Self::UndeadScourge974 => 974,
            Self::CenarionCircle994 => 994,
            Self::ThunderBluff995 => 995,
            Self::CenarionCircle996 => 996,
            Self::ShatterspearTrolls => 1014,
            Self::ShatterspearTrolls1015 => 1015,
            Self::HordeGeneric1034 => 1034,
            Self::AllianceGeneric1054 => 1054,
            Self::AllianceGeneric1055 => 1055,
            Self::Orgrimmar1074 => 1074,
            Self::Theramore1075 => 1075,
            Self::Darnassus1076 => 1076,
            Self::Theramore1077 => 1077,
            Self::Stormwind1078 => 1078,
            Self::Friendly1080 => 1080,
            Self::Elemental1081 => 1081,
            Self::BeastBoar => 1094,
            Self::TrainingDummy1095 => 1095,
            Self::Theramore1096 => 1096,
            Self::Darnassus1097 => 1097,
            Self::DragonflightBlackBait => 1114,
            Self::Undercity1134 => 1134,
            Self::Undercity1154 => 1154,
            Self::Orgrimmar1174 => 1174,
            Self::BattlegroundNeutral => 1194,
            Self::FrostwolfClan => 1214,
            Self::FrostwolfClan1215 => 1215,
            Self::StormpikeGuard => 1216,
            Self::StormpikeGuard1217 => 1217,
            Self::SulfuronFirelords => 1234,
            Self::SulfuronFirelords1235 => 1235,
            Self::SulfuronFirelords1236 => 1236,
            Self::CenarionCircle1254 => 1254,
            Self::Creature1274 => 1274,
            Self::Creature1275 => 1275,
            Self::Gizlock => 1294,
            Self::HordeGeneric1314 => 1314,
            Self::AllianceGeneric1315 => 1315,
            Self::StormpikeGuard1334 => 1334,
            Self::FrostwolfClan1335 => 1335,
            Self::Shendralar => 1354,
            Self::Shendralar1355 => 1355,
            Self::OgreCaptainKromcrush => 1374,
            Self::Treasure1375 => 1375,
            Self::DragonflightBlack1394 => 1394,
            Self::SilithidAttackers => 1395,
            Self::SpiritGuideAlliance => 1414,
            Self::SpiritGuideHorde => 1415,
            Self::Jaedenar => 1434,
            Self::Victim1454 => 1454,
            Self::ThoriumBrotherhood => 1474,
            Self::ThoriumBrotherhood1475 => 1475,
            Self::HordeGeneric1494 => 1494,
            Self::HordeGeneric1495 => 1495,
            Self::HordeGeneric1496 => 1496,
            Self::SilverwingSentinels => 1514,
            Self::WarsongOutriders => 1515,
            Self::StormpikeGuard1534 => 1534,
            Self::FrostwolfClan1554 => 1554,
            Self::DarkmoonFaire => 1555,
            Self::ZandalarTribe => 1574,
            Self::Stormwind1575 => 1575,
            Self::SilvermoonRemnant1576 => 1576,
            Self::TheLeagueOfArathor => 1577,
            Self::Darnassus1594 => 1594,
            Self::Orgrimmar1595 => 1595,
            Self::StormpikeGuard1596 => 1596,
            Self::FrostwolfClan1597 => 1597,
            Self::TheDefilers1598 => 1598,
            Self::TheLeagueOfArathor1599 => 1599,
            Self::Darnassus1600 => 1600,
            Self::BroodOfNozdormu1601 => 1601,
            Self::SilvermoonCity => 1602,
            Self::SilvermoonCity1603 => 1603,
            Self::SilvermoonCity1604 => 1604,
            Self::DragonflightBronze => 1605,
            Self::Creature1606 => 1606,
            Self::Creature1607 => 1607,
            Self::CenarionCircle1608 => 1608,
            Self::PlayerBloodElf => 1610,
            Self::Ironforge1611 => 1611,
            Self::Orgrimmar1612 => 1612,
            Self::MightOfKalimdor1613 => 1613,
            Self::Monster1614 => 1614,
            Self::SteamwheedleCartel => 1615,
            Self::RcObjects => 1616,
            Self::RcEnemies => 1617,
            Self::Ironforge1618 => 1618,
            Self::Orgrimmar1619 => 1619,
            Self::Enemy1620 => 1620,
            Self::Blue => 1621,
            Self::Red => 1622,
            Self::Tranquillien => 1623,
            Self::ArgentDawn1624 => 1624,
            Self::ArgentDawn1625 => 1625,
            Self::UndeadScourge1626 => 1626,
            Self::Farstriders => 1627,
            Self::Tranquillien1628 => 1628,
            Self::PlayerDraenei => 1629,
            Self::ScourgeInvaders => 1630,
            Self::ScourgeInvaders1634 => 1634,
            Self::SteamwheedleCartel1635 => 1635,
            Self::Farstriders1636 => 1636,
            Self::Farstriders1637 => 1637,
            Self::Exodar => 1638,
            Self::Exodar1639 => 1639,
            Self::Exodar1640 => 1640,
            Self::WarsongOutriders1641 => 1641,
            Self::SilverwingSentinels1642 => 1642,
        }
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::None => "NONE",
            Self::PlayerHuman => "PLAYER_HUMAN",
            Self::PlayerOrc => "PLAYER_ORC",
            Self::PlayerDwarf => "PLAYER_DWARF",
            Self::PlayerNightElf => "PLAYER_NIGHT_ELF",
            Self::PlayerUndead => "PLAYER_UNDEAD",
            Self::PlayerTauren => "PLAYER_TAUREN",
            Self::Creature => "CREATURE",
            Self::Escortee => "ESCORTEE",
            Self::Stormwind => "STORMWIND",
            Self::Stormwind12 => "STORMWIND_12",
            Self::Monster => "MONSTER",
            Self::Creature15 => "CREATURE_15",
            Self::Monster16 => "MONSTER_16",
            Self::DefiasBrotherhood => "DEFIAS_BROTHERHOOD",
            Self::Murloc => "MURLOC",
            Self::GnollRedridge => "GNOLL_REDRIDGE",
            Self::GnollRiverpaw => "GNOLL_RIVERPAW",
            Self::UndeadScourge => "UNDEAD_SCOURGE",
            Self::BeastSpider => "BEAST_SPIDER",
            Self::GnomereganExiles => "GNOMEREGAN_EXILES",
            Self::Worgen => "WORGEN",
            Self::Kobold => "KOBOLD",
            Self::Kobold26 => "KOBOLD_26",
            Self::DefiasBrotherhood27 => "DEFIAS_BROTHERHOOD_27",
            Self::TrollBloodscalp => "TROLL_BLOODSCALP",
            Self::Orgrimmar => "ORGRIMMAR",
            Self::TrollSkullsplitter => "TROLL_SKULLSPLITTER",
            Self::Prey => "PREY",
            Self::BeastWolf => "BEAST_WOLF",
            Self::Escortee33 => "ESCORTEE_33",
            Self::DefiasBrotherhood34 => "DEFIAS_BROTHERHOOD_34",
            Self::Friendly => "FRIENDLY",
            Self::Trogg => "TROGG",
            Self::TrollFrostmane => "TROLL_FROSTMANE",
            Self::BeastWolf38 => "BEAST_WOLF_38",
            Self::GnollShadowhide => "GNOLL_SHADOWHIDE",
            Self::OrcBlackrock => "ORC_BLACKROCK",
            Self::Villian => "VILLIAN",
            Self::Victim => "VICTIM",
            Self::Villian43 => "VILLIAN_43",
            Self::BeastBear => "BEAST_BEAR",
            Self::Ogre => "OGRE",
            Self::KurzensMercenaries => "KURZENS_MERCENARIES",
            Self::VentureCompany => "VENTURE_COMPANY",
            Self::BeastRaptor => "BEAST_RAPTOR",
            Self::Basilisk => "BASILISK",
            Self::DragonflightGreen => "DRAGONFLIGHT_GREEN",
            Self::LostOnes => "LOST_ONES",
            Self::GizlocksDummy => "GIZLOCKS_DUMMY",
            Self::HumanNightWatch => "HUMAN_NIGHT_WATCH",
            Self::DarkIronDwarves => "DARK_IRON_DWARVES",
            Self::Ironforge => "IRONFORGE",
            Self::HumanNightWatch56 => "HUMAN_NIGHT_WATCH_56",
            Self::Ironforge57 => "IRONFORGE_57",
            Self::Creature58 => "CREATURE_58",
            Self::Trogg59 => "TROGG_59",
            Self::DragonflightRed => "DRAGONFLIGHT_RED",
            Self::GnollMosshide => "GNOLL_MOSSHIDE",
            Self::OrcDragonmaw => "ORC_DRAGONMAW",
            Self::GnomeLeper => "GNOME_LEPER",
            Self::GnomereganExiles64 => "GNOMEREGAN_EXILES_64",
            Self::Orgrimmar65 => "ORGRIMMAR_65",
            Self::Leopard => "LEOPARD",
            Self::ScarletCrusade => "SCARLET_CRUSADE",
            Self::Undercity => "UNDERCITY",
            Self::Ratchet => "RATCHET",
            Self::GnollRothide => "GNOLL_ROTHIDE",
            Self::Undercity71 => "UNDERCITY_71",
            Self::BeastGorilla => "BEAST_GORILLA",
            Self::BeastCarrionBird => "BEAST_CARRION_BIRD",
            Self::Naga => "NAGA",
            Self::Dalaran => "DALARAN",
            Self::ForlornSpirit => "FORLORN_SPIRIT",
            Self::Darkhowl => "DARKHOWL",
            Self::Darnassus => "DARNASSUS",
            Self::Darnassus80 => "DARNASSUS_80",
            Self::Grell => "GRELL",
            Self::Furbolg => "FURBOLG",
            Self::HordeGeneric => "HORDE_GENERIC",
            Self::AllianceGeneric => "ALLIANCE_GENERIC",
            Self::Orgrimmar85 => "ORGRIMMAR_85",
            Self::GizlocksCharm => "GIZLOCKS_CHARM",
            Self::Syndicate => "SYNDICATE",
            Self::HillsbradMilitia => "HILLSBRAD_MILITIA",
            Self::ScarletCrusade89 => "SCARLET_CRUSADE_89",
            Self::Demon => "DEMON",
            Self::Elemental => "ELEMENTAL",
            Self::Spirit => "SPIRIT",
            Self::Monster93 => "MONSTER_93",
            Self::Treasure => "TREASURE",
            Self::GnollMudsnout => "GNOLL_MUDSNOUT",
            Self::HillsbradSouthshoreMayor => "HILLSBRAD_SOUTHSHORE_MAYOR",
            Self::Syndicate97 => "SYNDICATE_97",
            Self::Undercity98 => "UNDERCITY_98",
            Self::Victim99 => "VICTIM_99",
            Self::Treasure100 => "TREASURE_100",
            Self::Treasure101 => "TREASURE_101",
            Self::Treasure102 => "TREASURE_102",
            Self::DragonflightBlack => "DRAGONFLIGHT_BLACK",
            Self::ThunderBluff => "THUNDER_BLUFF",
            Self::ThunderBluff105 => "THUNDER_BLUFF_105",
            Self::HordeGeneric106 => "HORDE_GENERIC_106",
            Self::TrollFrostmane107 => "TROLL_FROSTMANE_107",
            Self::Syndicate108 => "SYNDICATE_108",
            Self::QuilboarRazormane2 => "QUILBOAR_RAZORMANE_2",
            Self::QuilboarRazormane2110 => "QUILBOAR_RAZORMANE_2_110",
            Self::QuilboarBristleback => "QUILBOAR_BRISTLEBACK",
            Self::QuilboarBristleback112 => "QUILBOAR_BRISTLEBACK_112",
            Self::Escortee113 => "ESCORTEE_113",
            Self::Treasure114 => "TREASURE_114",
            Self::PlayerGnome => "PLAYER_GNOME",
            Self::PlayerTroll => "PLAYER_TROLL",
            Self::Undercity118 => "UNDERCITY_118",
            Self::BloodsailBuccaneers => "BLOODSAIL_BUCCANEERS",
            Self::BootyBay => "BOOTY_BAY",
            Self::BootyBay121 => "BOOTY_BAY_121",
            Self::Ironforge122 => "IRONFORGE_122",
            Self::Stormwind123 => "STORMWIND_123",
            Self::Darnassus124 => "DARNASSUS_124",
            Self::Orgrimmar125 => "ORGRIMMAR_125",
            Self::DarkspearTrolls => "DARKSPEAR_TROLLS",
            Self::Villian127 => "VILLIAN_127",
            Self::Blackfathom => "BLACKFATHOM",
            Self::Makrura => "MAKRURA",
            Self::CentaurKolkar => "CENTAUR_KOLKAR",
            Self::CentaurGalak => "CENTAUR_GALAK",
            Self::GelkisClanCentaur => "GELKIS_CLAN_CENTAUR",
            Self::MagramClanCentaur => "MAGRAM_CLAN_CENTAUR",
            Self::Maraudine => "MARAUDINE",
            Self::Monster148 => "MONSTER_148",
            Self::Theramore => "THERAMORE",
            Self::Theramore150 => "THERAMORE_150",
            Self::Theramore151 => "THERAMORE_151",
            Self::QuilboarRazorfen => "QUILBOAR_RAZORFEN",
            Self::QuilboarRazorfen153 => "QUILBOAR_RAZORFEN_153",
            Self::QuilboarDeathshead => "QUILBOAR_DEATHSHEAD",
            Self::Enemy => "ENEMY",
            Self::Ambient => "AMBIENT",
            Self::Creature189 => "CREATURE_189",
            Self::Ambient190 => "AMBIENT_190",
            Self::NethergardeCaravan => "NETHERGARDE_CARAVAN",
            Self::NethergardeCaravan209 => "NETHERGARDE_CARAVAN_209",
            Self::AllianceGeneric210 => "ALLIANCE_GENERIC_210",
            Self::SouthseaFreebooters => "SOUTHSEA_FREEBOOTERS",
            Self::Escortee231 => "ESCORTEE_231",
            Self::Escortee232 => "ESCORTEE_232",
            Self::UndeadScourge233 => "UNDEAD_SCOURGE_233",
            Self::Escortee250 => "ESCORTEE_250",
            Self::WailingCaverns => "WAILING_CAVERNS",
            Self::Escortee290 => "ESCORTEE_290",
            Self::Silithid => "SILITHID",
            Self::Silithid311 => "SILITHID_311",
            Self::BeastSpider312 => "BEAST_SPIDER_312",
            Self::WailingCaverns330 => "WAILING_CAVERNS_330",
            Self::Blackfathom350 => "BLACKFATHOM_350",
            Self::ArmiesOfCthun => "ARMIES_OF_CTHUN",
            Self::SilvermoonRemnant => "SILVERMOON_REMNANT",
            Self::BootyBay390 => "BOOTY_BAY_390",
            Self::Basilisk410 => "BASILISK_410",
            Self::BeastBat => "BEAST_BAT",
            Self::TheDefilers => "THE_DEFILERS",
            Self::Scorpid => "SCORPID",
            Self::TimbermawHold => "TIMBERMAW_HOLD",
            Self::Titan => "TITAN",
            Self::Titan416 => "TITAN_416",
            Self::TaskmasterFizzule => "TASKMASTER_FIZZULE",
            Self::WailingCaverns450 => "WAILING_CAVERNS_450",
            Self::Titan470 => "TITAN_470",
            Self::Ravenholdt => "RAVENHOLDT",
            Self::Syndicate472 => "SYNDICATE_472",
            Self::Ravenholdt473 => "RAVENHOLDT_473",
            Self::Gadgetzan => "GADGETZAN",
            Self::Gadgetzan475 => "GADGETZAN_475",
            Self::GnomereganBug => "GNOMEREGAN_BUG",
            Self::Escortee495 => "ESCORTEE_495",
            Self::Harpy => "HARPY",
            Self::AllianceGeneric534 => "ALLIANCE_GENERIC_534",
            Self::BurningBlade => "BURNING_BLADE",
            Self::ShadowsilkPoacher => "SHADOWSILK_POACHER",
            Self::SearingSpider => "SEARING_SPIDER",
            Self::Trogg594 => "TROGG_594",
            Self::Victim614 => "VICTIM_614",
            Self::Monster634 => "MONSTER_634",
            Self::CenarionCircle => "CENARION_CIRCLE",
            Self::TimbermawHold636 => "TIMBERMAW_HOLD_636",
            Self::Ratchet637 => "RATCHET_637",
            Self::TrollWitherbark => "TROLL_WITHERBARK",
            Self::CentaurKolkar655 => "CENTAUR_KOLKAR_655",
            Self::DarkIronDwarves674 => "DARK_IRON_DWARVES_674",
            Self::AllianceGeneric694 => "ALLIANCE_GENERIC_694",
            Self::HydraxianWaterlords => "HYDRAXIAN_WATERLORDS",
            Self::HordeGeneric714 => "HORDE_GENERIC_714",
            Self::DarkIronDwarves734 => "DARK_IRON_DWARVES_734",
            Self::GoblinDarkIronBarPatron => "GOBLIN_DARK_IRON_BAR_PATRON",
            Self::GoblinDarkIronBarPatron736 => "GOBLIN_DARK_IRON_BAR_PATRON_736",
            Self::DarkIronDwarves754 => "DARK_IRON_DWARVES_754",
            Self::Escortee774 => "ESCORTEE_774",
            Self::Escortee775 => "ESCORTEE_775",
            Self::BroodOfNozdormu => "BROOD_OF_NOZDORMU",
            Self::MightOfKalimdor => "MIGHT_OF_KALIMDOR",
            Self::Giant => "GIANT",
            Self::ArgentDawn => "ARGENT_DAWN",
            Self::TrollVilebranch => "TROLL_VILEBRANCH",
            Self::ArgentDawn814 => "ARGENT_DAWN_814",
            Self::Elemental834 => "ELEMENTAL_834",
            Self::Everlook => "EVERLOOK",
            Self::Everlook855 => "EVERLOOK_855",
            Self::WintersaberTrainers => "WINTERSABER_TRAINERS",
            Self::GnomereganExiles875 => "GNOMEREGAN_EXILES_875",
            Self::DarkspearTrolls876 => "DARKSPEAR_TROLLS_876",
            Self::DarkspearTrolls877 => "DARKSPEAR_TROLLS_877",
            Self::Theramore894 => "THERAMORE_894",
            Self::TrainingDummy => "TRAINING_DUMMY",
            Self::FurbolgUncorrupted => "FURBOLG_UNCORRUPTED",
            Self::Demon954 => "DEMON_954",
            Self::UndeadScourge974 => "UNDEAD_SCOURGE_974",
            Self::CenarionCircle994 => "CENARION_CIRCLE_994",
            Self::ThunderBluff995 => "THUNDER_BLUFF_995",
            Self::CenarionCircle996 => "CENARION_CIRCLE_996",
            Self::ShatterspearTrolls => "SHATTERSPEAR_TROLLS",
            Self::ShatterspearTrolls1015 => "SHATTERSPEAR_TROLLS_1015",
            Self::HordeGeneric1034 => "HORDE_GENERIC_1034",
            Self::AllianceGeneric1054 => "ALLIANCE_GENERIC_1054",
            Self::AllianceGeneric1055 => "ALLIANCE_GENERIC_1055",
            Self::Orgrimmar1074 => "ORGRIMMAR_1074",
            Self::Theramore1075 => "THERAMORE_1075",
            Self::Darnassus1076 => "DARNASSUS_1076",
            Self::Theramore1077 => "THERAMORE_1077",
            Self::Stormwind1078 => "STORMWIND_1078",
            Self::Friendly1080 => "FRIENDLY_1080",
            Self::Elemental1081 => "ELEMENTAL_1081",
            Self::BeastBoar => "BEAST_BOAR",
            Self::TrainingDummy1095 => "TRAINING_DUMMY_1095",
            Self::Theramore1096 => "THERAMORE_1096",
            Self::Darnassus1097 => "DARNASSUS_1097",
            Self::DragonflightBlackBait => "DRAGONFLIGHT_BLACK_BAIT",
            Self::Undercity1134 => "UNDERCITY_1134",
            Self::Undercity1154 => "UNDERCITY_1154",
            Self::Orgrimmar1174 => "ORGRIMMAR_1174",
            Self::BattlegroundNeutral => "BATTLEGROUND_NEUTRAL",
            Self::FrostwolfClan => "FROSTWOLF_CLAN",
            Self::FrostwolfClan1215 => "FROSTWOLF_CLAN_1215",
            Self::StormpikeGuard => "STORMPIKE_GUARD",
            Self::StormpikeGuard1217 => "STORMPIKE_GUARD_1217",
            Self::SulfuronFirelords => "SULFURON_FIRELORDS",
            Self::SulfuronFirelords1235 => "SULFURON_FIRELORDS_1235",
            Self::SulfuronFirelords1236 => "SULFURON_FIRELORDS_1236",
            Self::CenarionCircle1254 => "CENARION_CIRCLE_1254",
            Self::Creature1274 => "CREATURE_1274",
            Self::Creature1275 => "CREATURE_1275",
            Self::Gizlock => "GIZLOCK",
            Self::HordeGeneric1314 => "HORDE_GENERIC_1314",
            Self::AllianceGeneric1315 => "ALLIANCE_GENERIC_1315",
            Self::StormpikeGuard1334 => "STORMPIKE_GUARD_1334",
            Self::FrostwolfClan1335 => "FROSTWOLF_CLAN_1335",
            Self::Shendralar => "SHENDRALAR",
            Self::Shendralar1355 => "SHENDRALAR_1355",
            Self::OgreCaptainKromcrush => "OGRE_CAPTAIN_KROMCRUSH",
            Self::Treasure1375 => "TREASURE_1375",
            Self::DragonflightBlack1394 => "DRAGONFLIGHT_BLACK_1394",
            Self::SilithidAttackers => "SILITHID_ATTACKERS",
            Self::SpiritGuideAlliance => "SPIRIT_GUIDE_ALLIANCE",
            Self::SpiritGuideHorde => "SPIRIT_GUIDE_HORDE",
            Self::Jaedenar => "JAEDENAR",
            Self::Victim1454 => "VICTIM_1454",
            Self::ThoriumBrotherhood => "THORIUM_BROTHERHOOD",
            Self::ThoriumBrotherhood1475 => "THORIUM_BROTHERHOOD_1475",
            Self::HordeGeneric1494 => "HORDE_GENERIC_1494",
            Self::HordeGeneric1495 => "HORDE_GENERIC_1495",
            Self::HordeGeneric1496 => "HORDE_GENERIC_1496",
            Self::SilverwingSentinels => "SILVERWING_SENTINELS",
            Self::WarsongOutriders => "WARSONG_OUTRIDERS",
            Self::StormpikeGuard1534 => "STORMPIKE_GUARD_1534",
            Self::FrostwolfClan1554 => "FROSTWOLF_CLAN_1554",
            Self::DarkmoonFaire => "DARKMOON_FAIRE",
            Self::ZandalarTribe => "ZANDALAR_TRIBE",
            Self::Stormwind1575 => "STORMWIND_1575",
            Self::SilvermoonRemnant1576 => "SILVERMOON_REMNANT_1576",
            Self::TheLeagueOfArathor => "THE_LEAGUE_OF_ARATHOR",
            Self::Darnassus1594 => "DARNASSUS_1594",
            Self::Orgrimmar1595 => "ORGRIMMAR_1595",
            Self::StormpikeGuard1596 => "STORMPIKE_GUARD_1596",
            Self::FrostwolfClan1597 => "FROSTWOLF_CLAN_1597",
            Self::TheDefilers1598 => "THE_DEFILERS_1598",
            Self::TheLeagueOfArathor1599 => "THE_LEAGUE_OF_ARATHOR_1599",
            Self::Darnassus1600 => "DARNASSUS_1600",
            Self::BroodOfNozdormu1601 => "BROOD_OF_NOZDORMU_1601",
            Self::SilvermoonCity => "SILVERMOON_CITY",
            Self::SilvermoonCity1603 => "SILVERMOON_CITY_1603",
            Self::SilvermoonCity1604 => "SILVERMOON_CITY_1604",
            Self::DragonflightBronze => "DRAGONFLIGHT_BRONZE",
            Self::Creature1606 => "CREATURE_1606",
            Self::Creature1607 => "CREATURE_1607",
            Self::CenarionCircle1608 => "CENARION_CIRCLE_1608",
            Self::PlayerBloodElf => "PLAYER_BLOOD_ELF",
            Self::Ironforge1611 => "IRONFORGE_1611",
            Self::Orgrimmar1612 => "ORGRIMMAR_1612",
            Self::MightOfKalimdor1613 => "MIGHT_OF_KALIMDOR_1613",
            Self::Monster1614 => "MONSTER_1614",
            Self::SteamwheedleCartel => "STEAMWHEEDLE_CARTEL",
            Self::RcObjects => "RC_OBJECTS",
            Self::RcEnemies => "RC_ENEMIES",
            Self::Ironforge1618 => "IRONFORGE_1618",
            Self::Orgrimmar1619 => "ORGRIMMAR_1619",
            Self::Enemy1620 => "ENEMY_1620",
            Self::Blue => "BLUE",
            Self::Red => "RED",
            Self::Tranquillien => "TRANQUILLIEN",
            Self::ArgentDawn1624 => "ARGENT_DAWN_1624",
            Self::ArgentDawn1625 => "ARGENT_DAWN_1625",
            Self::UndeadScourge1626 => "UNDEAD_SCOURGE_1626",
            Self::Farstriders => "FARSTRIDERS",
            Self::Tranquillien1628 => "TRANQUILLIEN_1628",
            Self::PlayerDraenei => "PLAYER_DRAENEI",
            Self::ScourgeInvaders => "SCOURGE_INVADERS",
            Self::ScourgeInvaders1634 => "SCOURGE_INVADERS_1634",
            Self::SteamwheedleCartel1635 => "STEAMWHEEDLE_CARTEL_1635",
            Self::Farstriders1636 => "FARSTRIDERS_1636",
            Self::Farstriders1637 => "FARSTRIDERS_1637",
            Self::Exodar => "EXODAR",
            Self::Exodar1639 => "EXODAR_1639",
            Self::Exodar1640 => "EXODAR_1640",
            Self::WarsongOutriders1641 => "WARSONG_OUTRIDERS_1641",
            Self::SilverwingSentinels1642 => "SILVERWING_SENTINELS_1642",
        }
    }

    pub fn from_protocol(value: u32) -> Option<Self> {
        match value {
            0 => Some(Self::None),
            1 => Some(Self::PlayerHuman),
            2 => Some(Self::PlayerOrc),
            3 => Some(Self::PlayerDwarf),
            4 => Some(Self::PlayerNightElf),
            5 => Some(Self::PlayerUndead),
            6 => Some(Self::PlayerTauren),
            7 => Some(Self::Creature),
            10 => Some(Self::Escortee),
            11 => Some(Self::Stormwind),
            12 => Some(Self::Stormwind12),
            14 => Some(Self::Monster),
            15 => Some(Self::Creature15),
            16 => Some(Self::Monster16),
            17 => Some(Self::DefiasBrotherhood),
            18 => Some(Self::Murloc),
            19 => Some(Self::GnollRedridge),
            20 => Some(Self::GnollRiverpaw),
            21 => Some(Self::UndeadScourge),
            22 => Some(Self::BeastSpider),
            23 => Some(Self::GnomereganExiles),
            24 => Some(Self::Worgen),
            25 => Some(Self::Kobold),
            26 => Some(Self::Kobold26),
            27 => Some(Self::DefiasBrotherhood27),
            28 => Some(Self::TrollBloodscalp),
            29 => Some(Self::Orgrimmar),
            30 => Some(Self::TrollSkullsplitter),
            31 => Some(Self::Prey),
            32 => Some(Self::BeastWolf),
            33 => Some(Self::Escortee33),
            34 => Some(Self::DefiasBrotherhood34),
            35 => Some(Self::Friendly),
            36 => Some(Self::Trogg),
            37 => Some(Self::TrollFrostmane),
            38 => Some(Self::BeastWolf38),
            39 => Some(Self::GnollShadowhide),
            40 => Some(Self::OrcBlackrock),
            41 => Some(Self::Villian),
            42 => Some(Self::Victim),
            43 => Some(Self::Villian43),
            44 => Some(Self::BeastBear),
            45 => Some(Self::Ogre),
            46 => Some(Self::KurzensMercenaries),
            47 => Some(Self::VentureCompany),
            48 => Some(Self::BeastRaptor),
            49 => Some(Self::Basilisk),
            50 => Some(Self::DragonflightGreen),
            51 => Some(Self::LostOnes),
            52 => Some(Self::GizlocksDummy),
            53 => Some(Self::HumanNightWatch),
            54 => Some(Self::DarkIronDwarves),
            55 => Some(Self::Ironforge),
            56 => Some(Self::HumanNightWatch56),
            57 => Some(Self::Ironforge57),
            58 => Some(Self::Creature58),
            59 => Some(Self::Trogg59),
            60 => Some(Self::DragonflightRed),
            61 => Some(Self::GnollMosshide),
            62 => Some(Self::OrcDragonmaw),
            63 => Some(Self::GnomeLeper),
            64 => Some(Self::GnomereganExiles64),
            65 => Some(Self::Orgrimmar65),
            66 => Some(Self::Leopard),
            67 => Some(Self::ScarletCrusade),
            68 => Some(Self::Undercity),
            69 => Some(Self::Ratchet),
            70 => Some(Self::GnollRothide),
            71 => Some(Self::Undercity71),
            72 => Some(Self::BeastGorilla),
            73 => Some(Self::BeastCarrionBird),
            74 => Some(Self::Naga),
            76 => Some(Self::Dalaran),
            77 => Some(Self::ForlornSpirit),
            78 => Some(Self::Darkhowl),
            79 => Some(Self::Darnassus),
            80 => Some(Self::Darnassus80),
            81 => Some(Self::Grell),
            82 => Some(Self::Furbolg),
            83 => Some(Self::HordeGeneric),
            84 => Some(Self::AllianceGeneric),
            85 => Some(Self::Orgrimmar85),
            86 => Some(Self::GizlocksCharm),
            87 => Some(Self::Syndicate),
            88 => Some(Self::HillsbradMilitia),
            89 => Some(Self::ScarletCrusade89),
            90 => Some(Self::Demon),
            91 => Some(Self::Elemental),
            92 => Some(Self::Spirit),
            93 => Some(Self::Monster93),
            94 => Some(Self::Treasure),
            95 => Some(Self::GnollMudsnout),
            96 => Some(Self::HillsbradSouthshoreMayor),
            97 => Some(Self::Syndicate97),
            98 => Some(Self::Undercity98),
            99 => Some(Self::Victim99),
            100 => Some(Self::Treasure100),
            101 => Some(Self::Treasure101),
            102 => Some(Self::Treasure102),
            103 => Some(Self::DragonflightBlack),
            104 => Some(Self::ThunderBluff),
            105 => Some(Self::ThunderBluff105),
            106 => Some(Self::HordeGeneric106),
            107 => Some(Self::TrollFrostmane107),
            108 => Some(Self::Syndicate108),
            109 => Some(Self::QuilboarRazormane2),
            110 => Some(Self::QuilboarRazormane2110),
            111 => Some(Self::QuilboarBristleback),
            112 => Some(Self::QuilboarBristleback112),
            113 => Some(Self::Escortee113),
            114 => Some(Self::Treasure114),
            115 => Some(Self::PlayerGnome),
            116 => Some(Self::PlayerTroll),
            118 => Some(Self::Undercity118),
            119 => Some(Self::BloodsailBuccaneers),
            120 => Some(Self::BootyBay),
            121 => Some(Self::BootyBay121),
            122 => Some(Self::Ironforge122),
            123 => Some(Self::Stormwind123),
            124 => Some(Self::Darnassus124),
            125 => Some(Self::Orgrimmar125),
            126 => Some(Self::DarkspearTrolls),
            127 => Some(Self::Villian127),
            128 => Some(Self::Blackfathom),
            129 => Some(Self::Makrura),
            130 => Some(Self::CentaurKolkar),
            131 => Some(Self::CentaurGalak),
            132 => Some(Self::GelkisClanCentaur),
            133 => Some(Self::MagramClanCentaur),
            134 => Some(Self::Maraudine),
            148 => Some(Self::Monster148),
            149 => Some(Self::Theramore),
            150 => Some(Self::Theramore150),
            151 => Some(Self::Theramore151),
            152 => Some(Self::QuilboarRazorfen),
            153 => Some(Self::QuilboarRazorfen153),
            154 => Some(Self::QuilboarDeathshead),
            168 => Some(Self::Enemy),
            188 => Some(Self::Ambient),
            189 => Some(Self::Creature189),
            190 => Some(Self::Ambient190),
            208 => Some(Self::NethergardeCaravan),
            209 => Some(Self::NethergardeCaravan209),
            210 => Some(Self::AllianceGeneric210),
            230 => Some(Self::SouthseaFreebooters),
            231 => Some(Self::Escortee231),
            232 => Some(Self::Escortee232),
            233 => Some(Self::UndeadScourge233),
            250 => Some(Self::Escortee250),
            270 => Some(Self::WailingCaverns),
            290 => Some(Self::Escortee290),
            310 => Some(Self::Silithid),
            311 => Some(Self::Silithid311),
            312 => Some(Self::BeastSpider312),
            330 => Some(Self::WailingCaverns330),
            350 => Some(Self::Blackfathom350),
            370 => Some(Self::ArmiesOfCthun),
            371 => Some(Self::SilvermoonRemnant),
            390 => Some(Self::BootyBay390),
            410 => Some(Self::Basilisk410),
            411 => Some(Self::BeastBat),
            412 => Some(Self::TheDefilers),
            413 => Some(Self::Scorpid),
            414 => Some(Self::TimbermawHold),
            415 => Some(Self::Titan),
            416 => Some(Self::Titan416),
            430 => Some(Self::TaskmasterFizzule),
            450 => Some(Self::WailingCaverns450),
            470 => Some(Self::Titan470),
            471 => Some(Self::Ravenholdt),
            472 => Some(Self::Syndicate472),
            473 => Some(Self::Ravenholdt473),
            474 => Some(Self::Gadgetzan),
            475 => Some(Self::Gadgetzan475),
            494 => Some(Self::GnomereganBug),
            495 => Some(Self::Escortee495),
            514 => Some(Self::Harpy),
            534 => Some(Self::AllianceGeneric534),
            554 => Some(Self::BurningBlade),
            574 => Some(Self::ShadowsilkPoacher),
            575 => Some(Self::SearingSpider),
            594 => Some(Self::Trogg594),
            614 => Some(Self::Victim614),
            634 => Some(Self::Monster634),
            635 => Some(Self::CenarionCircle),
            636 => Some(Self::TimbermawHold636),
            637 => Some(Self::Ratchet637),
            654 => Some(Self::TrollWitherbark),
            655 => Some(Self::CentaurKolkar655),
            674 => Some(Self::DarkIronDwarves674),
            694 => Some(Self::AllianceGeneric694),
            695 => Some(Self::HydraxianWaterlords),
            714 => Some(Self::HordeGeneric714),
            734 => Some(Self::DarkIronDwarves734),
            735 => Some(Self::GoblinDarkIronBarPatron),
            736 => Some(Self::GoblinDarkIronBarPatron736),
            754 => Some(Self::DarkIronDwarves754),
            774 => Some(Self::Escortee774),
            775 => Some(Self::Escortee775),
            776 => Some(Self::BroodOfNozdormu),
            777 => Some(Self::MightOfKalimdor),
            778 => Some(Self::Giant),
            794 => Some(Self::ArgentDawn),
            795 => Some(Self::TrollVilebranch),
            814 => Some(Self::ArgentDawn814),
            834 => Some(Self::Elemental834),
            854 => Some(Self::Everlook),
            855 => Some(Self::Everlook855),
            874 => Some(Self::WintersaberTrainers),
            875 => Some(Self::GnomereganExiles875),
            876 => Some(Self::DarkspearTrolls876),
            877 => Some(Self::DarkspearTrolls877),
            894 => Some(Self::Theramore894),
            914 => Some(Self::TrainingDummy),
            934 => Some(Self::FurbolgUncorrupted),
            954 => Some(Self::Demon954),
            974 => Some(Self::UndeadScourge974),
            994 => Some(Self::CenarionCircle994),
            995 => Some(Self::ThunderBluff995),
            996 => Some(Self::CenarionCircle996),
            1014 => Some(Self::ShatterspearTrolls),
            1015 => Some(Self::ShatterspearTrolls1015),
            1034 => Some(Self::HordeGeneric1034),
            1054 => Some(Self::AllianceGeneric1054),
            1055 => Some(Self::AllianceGeneric1055),
            1074 => Some(Self::Orgrimmar1074),
            1075 => Some(Self::Theramore1075),
            1076 => Some(Self::Darnassus1076),
            1077 => Some(Self::Theramore1077),
            1078 => Some(Self::Stormwind1078),
            1080 => Some(Self::Friendly1080),
            1081 => Some(Self::Elemental1081),
            1094 => Some(Self::BeastBoar),
            1095 => Some(Self::TrainingDummy1095),
            1096 => Some(Self::Theramore1096),
            1097 => Some(Self::Darnassus1097),
            1114 => Some(Self::DragonflightBlackBait),
            1134 => Some(Self::Undercity1134),
            1154 => Some(Self::Undercity1154),
            1174 => Some(Self::Orgrimmar1174),
            1194 => Some(Self::BattlegroundNeutral),
            1214 => Some(Self::FrostwolfClan),
            1215 => Some(Self::FrostwolfClan1215),
            1216 => Some(Self::StormpikeGuard),
            1217 => Some(Self::StormpikeGuard1217),
            1234 => Some(Self::SulfuronFirelords),
            1235 => Some(Self::SulfuronFirelords1235),
            1236 => Some(Self::SulfuronFirelords1236),
            1254 => Some(Self::CenarionCircle1254),
            1274 => Some(Self::Creature1274),
            1275 => Some(Self::Creature1275),
            1294 => Some(Self::Gizlock),
            1314 => Some(Self::HordeGeneric1314),
            1315 => Some(Self::AllianceGeneric1315),
            1334 => Some(Self::StormpikeGuard1334),
            1335 => Some(Self::FrostwolfClan1335),
            1354 => Some(Self::Shendralar),
            1355 => Some(Self::Shendralar1355),
            1374 => Some(Self::OgreCaptainKromcrush),
            1375 => Some(Self::Treasure1375),
            1394 => Some(Self::DragonflightBlack1394),
            1395 => Some(Self::SilithidAttackers),
            1414 => Some(Self::SpiritGuideAlliance),
            1415 => Some(Self::SpiritGuideHorde),
            1434 => Some(Self::Jaedenar),
            1454 => Some(Self::Victim1454),
            1474 => Some(Self::ThoriumBrotherhood),
            1475 => Some(Self::ThoriumBrotherhood1475),
            1494 => Some(Self::HordeGeneric1494),
            1495 => Some(Self::HordeGeneric1495),
            1496 => Some(Self::HordeGeneric1496),
            1514 => Some(Self::SilverwingSentinels),
            1515 => Some(Self::WarsongOutriders),
            1534 => Some(Self::StormpikeGuard1534),
            1554 => Some(Self::FrostwolfClan1554),
            1555 => Some(Self::DarkmoonFaire),
            1574 => Some(Self::ZandalarTribe),
            1575 => Some(Self::Stormwind1575),
            1576 => Some(Self::SilvermoonRemnant1576),
            1577 => Some(Self::TheLeagueOfArathor),
            1594 => Some(Self::Darnassus1594),
            1595 => Some(Self::Orgrimmar1595),
            1596 => Some(Self::StormpikeGuard1596),
            1597 => Some(Self::FrostwolfClan1597),
            1598 => Some(Self::TheDefilers1598),
            1599 => Some(Self::TheLeagueOfArathor1599),
            1600 => Some(Self::Darnassus1600),
            1601 => Some(Self::BroodOfNozdormu1601),
            1602 => Some(Self::SilvermoonCity),
            1603 => Some(Self::SilvermoonCity1603),
            1604 => Some(Self::SilvermoonCity1604),
            1605 => Some(Self::DragonflightBronze),
            1606 => Some(Self::Creature1606),
            1607 => Some(Self::Creature1607),
            1608 => Some(Self::CenarionCircle1608),
            1610 => Some(Self::PlayerBloodElf),
            1611 => Some(Self::Ironforge1611),
            1612 => Some(Self::Orgrimmar1612),
            1613 => Some(Self::MightOfKalimdor1613),
            1614 => Some(Self::Monster1614),
            1615 => Some(Self::SteamwheedleCartel),
            1616 => Some(Self::RcObjects),
            1617 => Some(Self::RcEnemies),
            1618 => Some(Self::Ironforge1618),
            1619 => Some(Self::Orgrimmar1619),
            1620 => Some(Self::Enemy1620),
            1621 => Some(Self::Blue),
            1622 => Some(Self::Red),
            1623 => Some(Self::Tranquillien),
            1624 => Some(Self::ArgentDawn1624),
            1625 => Some(Self::ArgentDawn1625),
            1626 => Some(Self::UndeadScourge1626),
            1627 => Some(Self::Farstriders),
            1628 => Some(Self::Tranquillien1628),
            1629 => Some(Self::PlayerDraenei),
            1630 => Some(Self::ScourgeInvaders),
            1634 => Some(Self::ScourgeInvaders1634),
            1635 => Some(Self::SteamwheedleCartel1635),
            1636 => Some(Self::Farstriders1636),
            1637 => Some(Self::Farstriders1637),
            1638 => Some(Self::Exodar),
            1639 => Some(Self::Exodar1639),
            1640 => Some(Self::Exodar1640),
            1641 => Some(Self::WarsongOutriders1641),
            1642 => Some(Self::SilverwingSentinels1642),
            _ => None,
        }
    }

    pub fn from_str(value: &str) -> Option<Self> {
        match value {
            "NONE" => Some(Self::None),
            "PLAYER_HUMAN" => Some(Self::PlayerHuman),
            "PLAYER_ORC" => Some(Self::PlayerOrc),
            "PLAYER_DWARF" => Some(Self::PlayerDwarf),
            "PLAYER_NIGHT_ELF" => Some(Self::PlayerNightElf),
            "PLAYER_UNDEAD" => Some(Self::PlayerUndead),
            "PLAYER_TAUREN" => Some(Self::PlayerTauren),
            "CREATURE" => Some(Self::Creature),
            "ESCORTEE" => Some(Self::Escortee),
            "STORMWIND" => Some(Self::Stormwind),
            "STORMWIND_12" => Some(Self::Stormwind12),
            "MONSTER" => Some(Self::Monster),
            "CREATURE_15" => Some(Self::Creature15),
            "MONSTER_16" => Some(Self::Monster16),
            "DEFIAS_BROTHERHOOD" => Some(Self::DefiasBrotherhood),
            "MURLOC" => Some(Self::Murloc),
            "GNOLL_REDRIDGE" => Some(Self::GnollRedridge),
            "GNOLL_RIVERPAW" => Some(Self::GnollRiverpaw),
            "UNDEAD_SCOURGE" => Some(Self::UndeadScourge),
            "BEAST_SPIDER" => Some(Self::BeastSpider),
            "GNOMEREGAN_EXILES" => Some(Self::GnomereganExiles),
            "WORGEN" => Some(Self::Worgen),
            "KOBOLD" => Some(Self::Kobold),
            "KOBOLD_26" => Some(Self::Kobold26),
            "DEFIAS_BROTHERHOOD_27" => Some(Self::DefiasBrotherhood27),
            "TROLL_BLOODSCALP" => Some(Self::TrollBloodscalp),
            "ORGRIMMAR" => Some(Self::Orgrimmar),
            "TROLL_SKULLSPLITTER" => Some(Self::TrollSkullsplitter),
            "PREY" => Some(Self::Prey),
            "BEAST_WOLF" => Some(Self::BeastWolf),
            "ESCORTEE_33" => Some(Self::Escortee33),
            "DEFIAS_BROTHERHOOD_34" => Some(Self::DefiasBrotherhood34),
            "FRIENDLY" => Some(Self::Friendly),
            "TROGG" => Some(Self::Trogg),
            "TROLL_FROSTMANE" => Some(Self::TrollFrostmane),
            "BEAST_WOLF_38" => Some(Self::BeastWolf38),
            "GNOLL_SHADOWHIDE" => Some(Self::GnollShadowhide),
            "ORC_BLACKROCK" => Some(Self::OrcBlackrock),
            "VILLIAN" => Some(Self::Villian),
            "VICTIM" => Some(Self::Victim),
            "VILLIAN_43" => Some(Self::Villian43),
            "BEAST_BEAR" => Some(Self::BeastBear),
            "OGRE" => Some(Self::Ogre),
            "KURZENS_MERCENARIES" => Some(Self::KurzensMercenaries),
            "VENTURE_COMPANY" => Some(Self::VentureCompany),
            "BEAST_RAPTOR" => Some(Self::BeastRaptor),
            "BASILISK" => Some(Self::Basilisk),
            "DRAGONFLIGHT_GREEN" => Some(Self::DragonflightGreen),
            "LOST_ONES" => Some(Self::LostOnes),
            "GIZLOCKS_DUMMY" => Some(Self::GizlocksDummy),
            "HUMAN_NIGHT_WATCH" => Some(Self::HumanNightWatch),
            "DARK_IRON_DWARVES" => Some(Self::DarkIronDwarves),
            "IRONFORGE" => Some(Self::Ironforge),
            "HUMAN_NIGHT_WATCH_56" => Some(Self::HumanNightWatch56),
            "IRONFORGE_57" => Some(Self::Ironforge57),
            "CREATURE_58" => Some(Self::Creature58),
            "TROGG_59" => Some(Self::Trogg59),
            "DRAGONFLIGHT_RED" => Some(Self::DragonflightRed),
            "GNOLL_MOSSHIDE" => Some(Self::GnollMosshide),
            "ORC_DRAGONMAW" => Some(Self::OrcDragonmaw),
            "GNOME_LEPER" => Some(Self::GnomeLeper),
            "GNOMEREGAN_EXILES_64" => Some(Self::GnomereganExiles64),
            "ORGRIMMAR_65" => Some(Self::Orgrimmar65),
            "LEOPARD" => Some(Self::Leopard),
            "SCARLET_CRUSADE" => Some(Self::ScarletCrusade),
            "UNDERCITY" => Some(Self::Undercity),
            "RATCHET" => Some(Self::Ratchet),
            "GNOLL_ROTHIDE" => Some(Self::GnollRothide),
            "UNDERCITY_71" => Some(Self::Undercity71),
            "BEAST_GORILLA" => Some(Self::BeastGorilla),
            "BEAST_CARRION_BIRD" => Some(Self::BeastCarrionBird),
            "NAGA" => Some(Self::Naga),
            "DALARAN" => Some(Self::Dalaran),
            "FORLORN_SPIRIT" => Some(Self::ForlornSpirit),
            "DARKHOWL" => Some(Self::Darkhowl),
            "DARNASSUS" => Some(Self::Darnassus),
            "DARNASSUS_80" => Some(Self::Darnassus80),
            "GRELL" => Some(Self::Grell),
            "FURBOLG" => Some(Self::Furbolg),
            "HORDE_GENERIC" => Some(Self::HordeGeneric),
            "ALLIANCE_GENERIC" => Some(Self::AllianceGeneric),
            "ORGRIMMAR_85" => Some(Self::Orgrimmar85),
            "GIZLOCKS_CHARM" => Some(Self::GizlocksCharm),
            "SYNDICATE" => Some(Self::Syndicate),
            "HILLSBRAD_MILITIA" => Some(Self::HillsbradMilitia),
            "SCARLET_CRUSADE_89" => Some(Self::ScarletCrusade89),
            "DEMON" => Some(Self::Demon),
            "ELEMENTAL" => Some(Self::Elemental),
            "SPIRIT" => Some(Self::Spirit),
            "MONSTER_93" => Some(Self::Monster93),
            "TREASURE" => Some(Self::Treasure),
            "GNOLL_MUDSNOUT" => Some(Self::GnollMudsnout),
            "HILLSBRAD_SOUTHSHORE_MAYOR" => Some(Self::HillsbradSouthshoreMayor),
            "SYNDICATE_97" => Some(Self::Syndicate97),
            "UNDERCITY_98" => Some(Self::Undercity98),
            "VICTIM_99" => Some(Self::Victim99),
            "TREASURE_100" => Some(Self::Treasure100),
            "TREASURE_101" => Some(Self::Treasure101),
            "TREASURE_102" => Some(Self::Treasure102),
            "DRAGONFLIGHT_BLACK" => Some(Self::DragonflightBlack),
            "THUNDER_BLUFF" => Some(Self::ThunderBluff),
            "THUNDER_BLUFF_105" => Some(Self::ThunderBluff105),
            "HORDE_GENERIC_106" => Some(Self::HordeGeneric106),
            "TROLL_FROSTMANE_107" => Some(Self::TrollFrostmane107),
            "SYNDICATE_108" => Some(Self::Syndicate108),
            "QUILBOAR_RAZORMANE_2" => Some(Self::QuilboarRazormane2),
            "QUILBOAR_RAZORMANE_2_110" => Some(Self::QuilboarRazormane2110),
            "QUILBOAR_BRISTLEBACK" => Some(Self::QuilboarBristleback),
            "QUILBOAR_BRISTLEBACK_112" => Some(Self::QuilboarBristleback112),
            "ESCORTEE_113" => Some(Self::Escortee113),
            "TREASURE_114" => Some(Self::Treasure114),
            "PLAYER_GNOME" => Some(Self::PlayerGnome),
            "PLAYER_TROLL" => Some(Self::PlayerTroll),
            "UNDERCITY_118" => Some(Self::Undercity118),
            "BLOODSAIL_BUCCANEERS" => Some(Self::BloodsailBuccaneers),
            "BOOTY_BAY" => Some(Self::BootyBay),
            "BOOTY_BAY_121" => Some(Self::BootyBay121),
            "IRONFORGE_122" => Some(Self::Ironforge122),
            "STORMWIND_123" => Some(Self::Stormwind123),
            "DARNASSUS_124" => Some(Self::Darnassus124),
            "ORGRIMMAR_125" => Some(Self::Orgrimmar125),
            "DARKSPEAR_TROLLS" => Some(Self::DarkspearTrolls),
            "VILLIAN_127" => Some(Self::Villian127),
            "BLACKFATHOM" => Some(Self::Blackfathom),
            "MAKRURA" => Some(Self::Makrura),
            "CENTAUR_KOLKAR" => Some(Self::CentaurKolkar),
            "CENTAUR_GALAK" => Some(Self::CentaurGalak),
            "GELKIS_CLAN_CENTAUR" => Some(Self::GelkisClanCentaur),
            "MAGRAM_CLAN_CENTAUR" => Some(Self::MagramClanCentaur),
            "MARAUDINE" => Some(Self::Maraudine),
            "MONSTER_148" => Some(Self::Monster148),
            "THERAMORE" => Some(Self::Theramore),
            "THERAMORE_150" => Some(Self::Theramore150),
            "THERAMORE_151" => Some(Self::Theramore151),
            "QUILBOAR_RAZORFEN" => Some(Self::QuilboarRazorfen),
            "QUILBOAR_RAZORFEN_153" => Some(Self::QuilboarRazorfen153),
            "QUILBOAR_DEATHSHEAD" => Some(Self::QuilboarDeathshead),
            "ENEMY" => Some(Self::Enemy),
            "AMBIENT" => Some(Self::Ambient),
            "CREATURE_189" => Some(Self::Creature189),
            "AMBIENT_190" => Some(Self::Ambient190),
            "NETHERGARDE_CARAVAN" => Some(Self::NethergardeCaravan),
            "NETHERGARDE_CARAVAN_209" => Some(Self::NethergardeCaravan209),
            "ALLIANCE_GENERIC_210" => Some(Self::AllianceGeneric210),
            "SOUTHSEA_FREEBOOTERS" => Some(Self::SouthseaFreebooters),
            "ESCORTEE_231" => Some(Self::Escortee231),
            "ESCORTEE_232" => Some(Self::Escortee232),
            "UNDEAD_SCOURGE_233" => Some(Self::UndeadScourge233),
            "ESCORTEE_250" => Some(Self::Escortee250),
            "WAILING_CAVERNS" => Some(Self::WailingCaverns),
            "ESCORTEE_290" => Some(Self::Escortee290),
            "SILITHID" => Some(Self::Silithid),
            "SILITHID_311" => Some(Self::Silithid311),
            "BEAST_SPIDER_312" => Some(Self::BeastSpider312),
            "WAILING_CAVERNS_330" => Some(Self::WailingCaverns330),
            "BLACKFATHOM_350" => Some(Self::Blackfathom350),
            "ARMIES_OF_CTHUN" => Some(Self::ArmiesOfCthun),
            "SILVERMOON_REMNANT" => Some(Self::SilvermoonRemnant),
            "BOOTY_BAY_390" => Some(Self::BootyBay390),
            "BASILISK_410" => Some(Self::Basilisk410),
            "BEAST_BAT" => Some(Self::BeastBat),
            "THE_DEFILERS" => Some(Self::TheDefilers),
            "SCORPID" => Some(Self::Scorpid),
            "TIMBERMAW_HOLD" => Some(Self::TimbermawHold),
            "TITAN" => Some(Self::Titan),
            "TITAN_416" => Some(Self::Titan416),
            "TASKMASTER_FIZZULE" => Some(Self::TaskmasterFizzule),
            "WAILING_CAVERNS_450" => Some(Self::WailingCaverns450),
            "TITAN_470" => Some(Self::Titan470),
            "RAVENHOLDT" => Some(Self::Ravenholdt),
            "SYNDICATE_472" => Some(Self::Syndicate472),
            "RAVENHOLDT_473" => Some(Self::Ravenholdt473),
            "GADGETZAN" => Some(Self::Gadgetzan),
            "GADGETZAN_475" => Some(Self::Gadgetzan475),
            "GNOMEREGAN_BUG" => Some(Self::GnomereganBug),
            "ESCORTEE_495" => Some(Self::Escortee495),
            "HARPY" => Some(Self::Harpy),
            "ALLIANCE_GENERIC_534" => Some(Self::AllianceGeneric534),
            "BURNING_BLADE" => Some(Self::BurningBlade),
            "SHADOWSILK_POACHER" => Some(Self::ShadowsilkPoacher),
            "SEARING_SPIDER" => Some(Self::SearingSpider),
            "TROGG_594" => Some(Self::Trogg594),
            "VICTIM_614" => Some(Self::Victim614),
            "MONSTER_634" => Some(Self::Monster634),
            "CENARION_CIRCLE" => Some(Self::CenarionCircle),
            "TIMBERMAW_HOLD_636" => Some(Self::TimbermawHold636),
            "RATCHET_637" => Some(Self::Ratchet637),
            "TROLL_WITHERBARK" => Some(Self::TrollWitherbark),
            "CENTAUR_KOLKAR_655" => Some(Self::CentaurKolkar655),
            "DARK_IRON_DWARVES_674" => Some(Self::DarkIronDwarves674),
            "ALLIANCE_GENERIC_694" => Some(Self::AllianceGeneric694),
            "HYDRAXIAN_WATERLORDS" => Some(Self::HydraxianWaterlords),
            "HORDE_GENERIC_714" => Some(Self::HordeGeneric714),
            "DARK_IRON_DWARVES_734" => Some(Self::DarkIronDwarves734),
            "GOBLIN_DARK_IRON_BAR_PATRON" => Some(Self::GoblinDarkIronBarPatron),
            "GOBLIN_DARK_IRON_BAR_PATRON_736" => Some(Self::GoblinDarkIronBarPatron736),
            "DARK_IRON_DWARVES_754" => Some(Self::DarkIronDwarves754),
            "ESCORTEE_774" => Some(Self::Escortee774),
            "ESCORTEE_775" => Some(Self::Escortee775),
            "BROOD_OF_NOZDORMU" => Some(Self::BroodOfNozdormu),
            "MIGHT_OF_KALIMDOR" => Some(Self::MightOfKalimdor),
            "GIANT" => Some(Self::Giant),
            "ARGENT_DAWN" => Some(Self::ArgentDawn),
            "TROLL_VILEBRANCH" => Some(Self::TrollVilebranch),
            "ARGENT_DAWN_814" => Some(Self::ArgentDawn814),
            "ELEMENTAL_834" => Some(Self::Elemental834),
            "EVERLOOK" => Some(Self::Everlook),
            "EVERLOOK_855" => Some(Self::Everlook855),
            "WINTERSABER_TRAINERS" => Some(Self::WintersaberTrainers),
            "GNOMEREGAN_EXILES_875" => Some(Self::GnomereganExiles875),
            "DARKSPEAR_TROLLS_876" => Some(Self::DarkspearTrolls876),
            "DARKSPEAR_TROLLS_877" => Some(Self::DarkspearTrolls877),
            "THERAMORE_894" => Some(Self::Theramore894),
            "TRAINING_DUMMY" => Some(Self::TrainingDummy),
            "FURBOLG_UNCORRUPTED" => Some(Self::FurbolgUncorrupted),
            "DEMON_954" => Some(Self::Demon954),
            "UNDEAD_SCOURGE_974" => Some(Self::UndeadScourge974),
            "CENARION_CIRCLE_994" => Some(Self::CenarionCircle994),
            "THUNDER_BLUFF_995" => Some(Self::ThunderBluff995),
            "CENARION_CIRCLE_996" => Some(Self::CenarionCircle996),
            "SHATTERSPEAR_TROLLS" => Some(Self::ShatterspearTrolls),
            "SHATTERSPEAR_TROLLS_1015" => Some(Self::ShatterspearTrolls1015),
            "HORDE_GENERIC_1034" => Some(Self::HordeGeneric1034),
            "ALLIANCE_GENERIC_1054" => Some(Self::AllianceGeneric1054),
            "ALLIANCE_GENERIC_1055" => Some(Self::AllianceGeneric1055),
            "ORGRIMMAR_1074" => Some(Self::Orgrimmar1074),
            "THERAMORE_1075" => Some(Self::Theramore1075),
            "DARNASSUS_1076" => Some(Self::Darnassus1076),
            "THERAMORE_1077" => Some(Self::Theramore1077),
            "STORMWIND_1078" => Some(Self::Stormwind1078),
            "FRIENDLY_1080" => Some(Self::Friendly1080),
            "ELEMENTAL_1081" => Some(Self::Elemental1081),
            "BEAST_BOAR" => Some(Self::BeastBoar),
            "TRAINING_DUMMY_1095" => Some(Self::TrainingDummy1095),
            "THERAMORE_1096" => Some(Self::Theramore1096),
            "DARNASSUS_1097" => Some(Self::Darnassus1097),
            "DRAGONFLIGHT_BLACK_BAIT" => Some(Self::DragonflightBlackBait),
            "UNDERCITY_1134" => Some(Self::Undercity1134),
            "UNDERCITY_1154" => Some(Self::Undercity1154),
            "ORGRIMMAR_1174" => Some(Self::Orgrimmar1174),
            "BATTLEGROUND_NEUTRAL" => Some(Self::BattlegroundNeutral),
            "FROSTWOLF_CLAN" => Some(Self::FrostwolfClan),
            "FROSTWOLF_CLAN_1215" => Some(Self::FrostwolfClan1215),
            "STORMPIKE_GUARD" => Some(Self::StormpikeGuard),
            "STORMPIKE_GUARD_1217" => Some(Self::StormpikeGuard1217),
            "SULFURON_FIRELORDS" => Some(Self::SulfuronFirelords),
            "SULFURON_FIRELORDS_1235" => Some(Self::SulfuronFirelords1235),
            "SULFURON_FIRELORDS_1236" => Some(Self::SulfuronFirelords1236),
            "CENARION_CIRCLE_1254" => Some(Self::CenarionCircle1254),
            "CREATURE_1274" => Some(Self::Creature1274),
            "CREATURE_1275" => Some(Self::Creature1275),
            "GIZLOCK" => Some(Self::Gizlock),
            "HORDE_GENERIC_1314" => Some(Self::HordeGeneric1314),
            "ALLIANCE_GENERIC_1315" => Some(Self::AllianceGeneric1315),
            "STORMPIKE_GUARD_1334" => Some(Self::StormpikeGuard1334),
            "FROSTWOLF_CLAN_1335" => Some(Self::FrostwolfClan1335),
            "SHENDRALAR" => Some(Self::Shendralar),
            "SHENDRALAR_1355" => Some(Self::Shendralar1355),
            "OGRE_CAPTAIN_KROMCRUSH" => Some(Self::OgreCaptainKromcrush),
            "TREASURE_1375" => Some(Self::Treasure1375),
            "DRAGONFLIGHT_BLACK_1394" => Some(Self::DragonflightBlack1394),
            "SILITHID_ATTACKERS" => Some(Self::SilithidAttackers),
            "SPIRIT_GUIDE_ALLIANCE" => Some(Self::SpiritGuideAlliance),
            "SPIRIT_GUIDE_HORDE" => Some(Self::SpiritGuideHorde),
            "JAEDENAR" => Some(Self::Jaedenar),
            "VICTIM_1454" => Some(Self::Victim1454),
            "THORIUM_BROTHERHOOD" => Some(Self::ThoriumBrotherhood),
            "THORIUM_BROTHERHOOD_1475" => Some(Self::ThoriumBrotherhood1475),
            "HORDE_GENERIC_1494" => Some(Self::HordeGeneric1494),
            "HORDE_GENERIC_1495" => Some(Self::HordeGeneric1495),
            "HORDE_GENERIC_1496" => Some(Self::HordeGeneric1496),
            "SILVERWING_SENTINELS" => Some(Self::SilverwingSentinels),
            "WARSONG_OUTRIDERS" => Some(Self::WarsongOutriders),
            "STORMPIKE_GUARD_1534" => Some(Self::StormpikeGuard1534),
            "FROSTWOLF_CLAN_1554" => Some(Self::FrostwolfClan1554),
            "DARKMOON_FAIRE" => Some(Self::DarkmoonFaire),
            "ZANDALAR_TRIBE" => Some(Self::ZandalarTribe),
            "STORMWIND_1575" => Some(Self::Stormwind1575),
            "SILVERMOON_REMNANT_1576" => Some(Self::SilvermoonRemnant1576),
            "THE_LEAGUE_OF_ARATHOR" => Some(Self::TheLeagueOfArathor),
            "DARNASSUS_1594" => Some(Self::Darnassus1594),
            "ORGRIMMAR_1595" => Some(Self::Orgrimmar1595),
            "STORMPIKE_GUARD_1596" => Some(Self::StormpikeGuard1596),
            "FROSTWOLF_CLAN_1597" => Some(Self::FrostwolfClan1597),
            "THE_DEFILERS_1598" => Some(Self::TheDefilers1598),
            "THE_LEAGUE_OF_ARATHOR_1599" => Some(Self::TheLeagueOfArathor1599),
            "DARNASSUS_1600" => Some(Self::Darnassus1600),
            "BROOD_OF_NOZDORMU_1601" => Some(Self::BroodOfNozdormu1601),
            "SILVERMOON_CITY" => Some(Self::SilvermoonCity),
            "SILVERMOON_CITY_1603" => Some(Self::SilvermoonCity1603),
            "SILVERMOON_CITY_1604" => Some(Self::SilvermoonCity1604),
            "DRAGONFLIGHT_BRONZE" => Some(Self::DragonflightBronze),
            "CREATURE_1606" => Some(Self::Creature1606),
            "CREATURE_1607" => Some(Self::Creature1607),
            "CENARION_CIRCLE_1608" => Some(Self::CenarionCircle1608),
            "PLAYER_BLOOD_ELF" => Some(Self::PlayerBloodElf),
            "IRONFORGE_1611" => Some(Self::Ironforge1611),
            "ORGRIMMAR_1612" => Some(Self::Orgrimmar1612),
            "MIGHT_OF_KALIMDOR_1613" => Some(Self::MightOfKalimdor1613),
            "MONSTER_1614" => Some(Self::Monster1614),
            "STEAMWHEEDLE_CARTEL" => Some(Self::SteamwheedleCartel),
            "RC_OBJECTS" => Some(Self::RcObjects),
            "RC_ENEMIES" => Some(Self::RcEnemies),
            "IRONFORGE_1618" => Some(Self::Ironforge1618),
            "ORGRIMMAR_1619" => Some(Self::Orgrimmar1619),
            "ENEMY_1620" => Some(Self::Enemy1620),
            "BLUE" => Some(Self::Blue),
            "RED" => Some(Self::Red),
            "TRANQUILLIEN" => Some(Self::Tranquillien),
            "ARGENT_DAWN_1624" => Some(Self::ArgentDawn1624),
            "ARGENT_DAWN_1625" => Some(Self::ArgentDawn1625),
            "UNDEAD_SCOURGE_1626" => Some(Self::UndeadScourge1626),
            "FARSTRIDERS" => Some(Self::Farstriders),
            "TRANQUILLIEN_1628" => Some(Self::Tranquillien1628),
            "PLAYER_DRAENEI" => Some(Self::PlayerDraenei),
            "SCOURGE_INVADERS" => Some(Self::ScourgeInvaders),
            "SCOURGE_INVADERS_1634" => Some(Self::ScourgeInvaders1634),
            "STEAMWHEEDLE_CARTEL_1635" => Some(Self::SteamwheedleCartel1635),
            "FARSTRIDERS_1636" => Some(Self::Farstriders1636),
            "FARSTRIDERS_1637" => Some(Self::Farstriders1637),
            "EXODAR" => Some(Self::Exodar),
            "EXODAR_1639" => Some(Self::Exodar1639),
            "EXODAR_1640" => Some(Self::Exodar1640),
            "WARSONG_OUTRIDERS_1641" => Some(Self::WarsongOutriders1641),
            "SILVERWING_SENTINELS_1642" => Some(Self::SilverwingSentinels1642),
            _ => None,
        }
    }

    pub const fn variants() -> [Self; 325] {
        [
            Self::None,
            Self::PlayerHuman,
            Self::PlayerOrc,
            Self::PlayerDwarf,
            Self::PlayerNightElf,
            Self::PlayerUndead,
            Self::PlayerTauren,
            Self::Creature,
            Self::Escortee,
            Self::Stormwind,
            Self::Stormwind12,
            Self::Monster,
            Self::Creature15,
            Self::Monster16,
            Self::DefiasBrotherhood,
            Self::Murloc,
            Self::GnollRedridge,
            Self::GnollRiverpaw,
            Self::UndeadScourge,
            Self::BeastSpider,
            Self::GnomereganExiles,
            Self::Worgen,
            Self::Kobold,
            Self::Kobold26,
            Self::DefiasBrotherhood27,
            Self::TrollBloodscalp,
            Self::Orgrimmar,
            Self::TrollSkullsplitter,
            Self::Prey,
            Self::BeastWolf,
            Self::Escortee33,
            Self::DefiasBrotherhood34,
            Self::Friendly,
            Self::Trogg,
            Self::TrollFrostmane,
            Self::BeastWolf38,
            Self::GnollShadowhide,
            Self::OrcBlackrock,
            Self::Villian,
            Self::Victim,
            Self::Villian43,
            Self::BeastBear,
            Self::Ogre,
            Self::KurzensMercenaries,
            Self::VentureCompany,
            Self::BeastRaptor,
            Self::Basilisk,
            Self::DragonflightGreen,
            Self::LostOnes,
            Self::GizlocksDummy,
            Self::HumanNightWatch,
            Self::DarkIronDwarves,
            Self::Ironforge,
            Self::HumanNightWatch56,
            Self::Ironforge57,
            Self::Creature58,
            Self::Trogg59,
            Self::DragonflightRed,
            Self::GnollMosshide,
            Self::OrcDragonmaw,
            Self::GnomeLeper,
            Self::GnomereganExiles64,
            Self::Orgrimmar65,
            Self::Leopard,
            Self::ScarletCrusade,
            Self::Undercity,
            Self::Ratchet,
            Self::GnollRothide,
            Self::Undercity71,
            Self::BeastGorilla,
            Self::BeastCarrionBird,
            Self::Naga,
            Self::Dalaran,
            Self::ForlornSpirit,
            Self::Darkhowl,
            Self::Darnassus,
            Self::Darnassus80,
            Self::Grell,
            Self::Furbolg,
            Self::HordeGeneric,
            Self::AllianceGeneric,
            Self::Orgrimmar85,
            Self::GizlocksCharm,
            Self::Syndicate,
            Self::HillsbradMilitia,
            Self::ScarletCrusade89,
            Self::Demon,
            Self::Elemental,
            Self::Spirit,
            Self::Monster93,
            Self::Treasure,
            Self::GnollMudsnout,
            Self::HillsbradSouthshoreMayor,
            Self::Syndicate97,
            Self::Undercity98,
            Self::Victim99,
            Self::Treasure100,
            Self::Treasure101,
            Self::Treasure102,
            Self::DragonflightBlack,
            Self::ThunderBluff,
            Self::ThunderBluff105,
            Self::HordeGeneric106,
            Self::TrollFrostmane107,
            Self::Syndicate108,
            Self::QuilboarRazormane2,
            Self::QuilboarRazormane2110,
            Self::QuilboarBristleback,
            Self::QuilboarBristleback112,
            Self::Escortee113,
            Self::Treasure114,
            Self::PlayerGnome,
            Self::PlayerTroll,
            Self::Undercity118,
            Self::BloodsailBuccaneers,
            Self::BootyBay,
            Self::BootyBay121,
            Self::Ironforge122,
            Self::Stormwind123,
            Self::Darnassus124,
            Self::Orgrimmar125,
            Self::DarkspearTrolls,
            Self::Villian127,
            Self::Blackfathom,
            Self::Makrura,
            Self::CentaurKolkar,
            Self::CentaurGalak,
            Self::GelkisClanCentaur,
            Self::MagramClanCentaur,
            Self::Maraudine,
            Self::Monster148,
            Self::Theramore,
            Self::Theramore150,
            Self::Theramore151,
            Self::QuilboarRazorfen,
            Self::QuilboarRazorfen153,
            Self::QuilboarDeathshead,
            Self::Enemy,
            Self::Ambient,
            Self::Creature189,
            Self::Ambient190,
            Self::NethergardeCaravan,
            Self::NethergardeCaravan209,
            Self::AllianceGeneric210,
            Self::SouthseaFreebooters,
            Self::Escortee231,
            Self::Escortee232,
            Self::UndeadScourge233,
            Self::Escortee250,
            Self::WailingCaverns,
            Self::Escortee290,
            Self::Silithid,
            Self::Silithid311,
            Self::BeastSpider312,
            Self::WailingCaverns330,
            Self::Blackfathom350,
            Self::ArmiesOfCthun,
            Self::SilvermoonRemnant,
            Self::BootyBay390,
            Self::Basilisk410,
            Self::BeastBat,
            Self::TheDefilers,
            Self::Scorpid,
            Self::TimbermawHold,
            Self::Titan,
            Self::Titan416,
            Self::TaskmasterFizzule,
            Self::WailingCaverns450,
            Self::Titan470,
            Self::Ravenholdt,
            Self::Syndicate472,
            Self::Ravenholdt473,
            Self::Gadgetzan,
            Self::Gadgetzan475,
            Self::GnomereganBug,
            Self::Escortee495,
            Self::Harpy,
            Self::AllianceGeneric534,
            Self::BurningBlade,
            Self::ShadowsilkPoacher,
            Self::SearingSpider,
            Self::Trogg594,
            Self::Victim614,
            Self::Monster634,
            Self::CenarionCircle,
            Self::TimbermawHold636,
            Self::Ratchet637,
            Self::TrollWitherbark,
            Self::CentaurKolkar655,
            Self::DarkIronDwarves674,
            Self::AllianceGeneric694,
            Self::HydraxianWaterlords,
            Self::HordeGeneric714,
            Self::DarkIronDwarves734,
            Self::GoblinDarkIronBarPatron,
            Self::GoblinDarkIronBarPatron736,
            Self::DarkIronDwarves754,
            Self::Escortee774,
            Self::Escortee775,
            Self::BroodOfNozdormu,
            Self::MightOfKalimdor,
            Self::Giant,
            Self::ArgentDawn,
            Self::TrollVilebranch,
            Self::ArgentDawn814,
            Self::Elemental834,
            Self::Everlook,
            Self::Everlook855,
            Self::WintersaberTrainers,
            Self::GnomereganExiles875,
            Self::DarkspearTrolls876,
            Self::DarkspearTrolls877,
            Self::Theramore894,
            Self::TrainingDummy,
            Self::FurbolgUncorrupted,
            Self::Demon954,
            Self::UndeadScourge974,
            Self::CenarionCircle994,
            Self::ThunderBluff995,
            Self::CenarionCircle996,
            Self::ShatterspearTrolls,
            Self::ShatterspearTrolls1015,
            Self::HordeGeneric1034,
            Self::AllianceGeneric1054,
            Self::AllianceGeneric1055,
            Self::Orgrimmar1074,
            Self::Theramore1075,
            Self::Darnassus1076,
            Self::Theramore1077,
            Self::Stormwind1078,
            Self::Friendly1080,
            Self::Elemental1081,
            Self::BeastBoar,
            Self::TrainingDummy1095,
            Self::Theramore1096,
            Self::Darnassus1097,
            Self::DragonflightBlackBait,
            Self::Undercity1134,
            Self::Undercity1154,
            Self::Orgrimmar1174,
            Self::BattlegroundNeutral,
            Self::FrostwolfClan,
            Self::FrostwolfClan1215,
            Self::StormpikeGuard,
            Self::StormpikeGuard1217,
            Self::SulfuronFirelords,
            Self::SulfuronFirelords1235,
            Self::SulfuronFirelords1236,
            Self::CenarionCircle1254,
            Self::Creature1274,
            Self::Creature1275,
            Self::Gizlock,
            Self::HordeGeneric1314,
            Self::AllianceGeneric1315,
            Self::StormpikeGuard1334,
            Self::FrostwolfClan1335,
            Self::Shendralar,
            Self::Shendralar1355,
            Self::OgreCaptainKromcrush,
            Self::Treasure1375,
            Self::DragonflightBlack1394,
            Self::SilithidAttackers,
            Self::SpiritGuideAlliance,
            Self::SpiritGuideHorde,
            Self::Jaedenar,
            Self::Victim1454,
            Self::ThoriumBrotherhood,
            Self::ThoriumBrotherhood1475,
            Self::HordeGeneric1494,
            Self::HordeGeneric1495,
            Self::HordeGeneric1496,
            Self::SilverwingSentinels,
            Self::WarsongOutriders,
            Self::StormpikeGuard1534,
            Self::FrostwolfClan1554,
            Self::DarkmoonFaire,
            Self::ZandalarTribe,
            Self::Stormwind1575,
            Self::SilvermoonRemnant1576,
            Self::TheLeagueOfArathor,
            Self::Darnassus1594,
            Self::Orgrimmar1595,
            Self::StormpikeGuard1596,
            Self::FrostwolfClan1597,
            Self::TheDefilers1598,
            Self::TheLeagueOfArathor1599,
            Self::Darnassus1600,
            Self::BroodOfNozdormu1601,
            Self::SilvermoonCity,
            Self::SilvermoonCity1603,
            Self::SilvermoonCity1604,
            Self::DragonflightBronze,
            Self::Creature1606,
            Self::Creature1607,
            Self::CenarionCircle1608,
            Self::PlayerBloodElf,
            Self::Ironforge1611,
            Self::Orgrimmar1612,
            Self::MightOfKalimdor1613,
            Self::Monster1614,
            Self::SteamwheedleCartel,
            Self::RcObjects,
            Self::RcEnemies,
            Self::Ironforge1618,
            Self::Orgrimmar1619,
            Self::Enemy1620,
            Self::Blue,
            Self::Red,
            Self::Tranquillien,
            Self::ArgentDawn1624,
            Self::ArgentDawn1625,
            Self::UndeadScourge1626,
            Self::Farstriders,
            Self::Tranquillien1628,
            Self::PlayerDraenei,
            Self::ScourgeInvaders,
            Self::ScourgeInvaders1634,
            Self::SteamwheedleCartel1635,
            Self::Farstriders1636,
            Self::Farstriders1637,
            Self::Exodar,
            Self::Exodar1639,
            Self::Exodar1640,
            Self::WarsongOutriders1641,
            Self::SilverwingSentinels1642,
        ]
    }
}

impl DbEnum for CreatureFaction {
    fn as_protocol(self) -> u32 {
        Self::as_protocol(self)
    }

    fn as_str(self) -> &'static str {
        Self::as_str(self)
    }

    fn from_protocol(value: u32) -> Option<Self> {
        Self::from_protocol(value)
    }

    fn from_str(value: &str) -> Option<Self> {
        Self::from_str(value)
    }
}
