[package]
name = "world-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
default-run = "world-server"

[dependencies]
anyhow.workspace = true
client-data.workspace = true
redis.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
wow-shared.workspace = true
wow_srp.workspace = true
wow_world_messages.workspace = true
